Found 20 items
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile10
-rw-r--r--   3 root supergroup  805306368 2019-02-20 03:09 /myfile11._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile12._COPYING_
-rw-r--r--   3 root supergroup  805306368 2019-02-20 03:09 /myfile13._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile14
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile15._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile16._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile17
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile18
-rw-r--r--   3 root supergroup  805306368 2019-02-20 03:09 /myfile19._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile2._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile20
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile3._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile4._COPYING_
-rw-r--r--   3 root supergroup  805306368 2019-02-20 03:09 /myfile5._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile6
-rw-r--r--   3 root supergroup  805306368 2019-02-20 03:09 /myfile7._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile8
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile9._COPYING_
file 10 has been put into HDFS
file 10 has been read from HDFS for 1 time
diff succeed!
file 10 has been read from HDFS for 2 time
diff succeed!
file 10 has been read from HDFS for 3 time
diff succeed!
file 10 has been read from HDFS for 4 time
diff succeed!
2019-02-20 03:10:56,612 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 906ms.
2019-02-20 03:10:57,521 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2692ms.
2019-02-20 03:11:00,216 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4791ms.
2019-02-20 03:11:05,012 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6895ms.
2019-02-20 03:11:11,910 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12462ms.
2019-02-20 03:11:24,374 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10214ms.
2019-02-20 03:11:34,591 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19318ms.
2019-02-20 03:11:53,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9551ms.
2019-02-20 03:12:03,465 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17635ms.
2019-02-20 03:12:21,102 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10930ms.
2019-02-20 03:12:32,034 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19415ms.
2019-02-20 03:12:51,452 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15059ms.
2019-02-20 03:13:06,514 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15412ms.
2019-02-20 03:13:21,929 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13030ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:13:47,199 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 949ms.
2019-02-20 03:13:48,150 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1882ms.
2019-02-20 03:13:50,034 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4347ms.
2019-02-20 03:13:54,387 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8087ms.
2019-02-20 03:14:02,477 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21559ms.
2019-02-20 03:14:24,038 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16965ms.
2019-02-20 03:14:41,006 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10409ms.
2019-02-20 03:14:51,417 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14050ms.
2019-02-20 03:15:05,469 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17388ms.
2019-02-20 03:15:22,860 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18606ms.
2019-02-20 03:15:41,468 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13463ms.
2019-02-20 03:15:54,934 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9951ms.
2019-02-20 03:16:04,888 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13771ms.
2019-02-20 03:16:18,661 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13010ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:16:43,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 674ms.
2019-02-20 03:16:44,599 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2841ms.
2019-02-20 03:16:47,442 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5474ms.
2019-02-20 03:16:52,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6611ms.
2019-02-20 03:16:59,535 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18575ms.
2019-02-20 03:17:18,113 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14142ms.
2019-02-20 03:17:32,258 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16163ms.
2019-02-20 03:17:48,424 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13845ms.
2019-02-20 03:18:02,271 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 19415ms.
2019-02-20 03:18:21,689 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15642ms.
2019-02-20 03:18:37,333 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19957ms.
2019-02-20 03:18:57,293 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15473ms.
2019-02-20 03:19:12,769 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13522ms.
2019-02-20 03:19:26,293 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17774ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:19:56,333 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 823ms.
2019-02-20 03:19:57,160 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1156ms.
2019-02-20 03:19:58,318 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2000ms.
2019-02-20 03:20:00,320 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9019ms.
2019-02-20 03:20:09,344 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9929ms.
2019-02-20 03:20:19,276 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8572ms.
2019-02-20 03:20:27,851 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16740ms.
2019-02-20 03:20:44,594 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20431ms.
2019-02-20 03:21:05,027 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20599ms.
2019-02-20 03:21:25,629 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13022ms.
2019-02-20 03:21:38,653 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14448ms.
2019-02-20 03:21:53,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 7806ms.
2019-02-20 03:22:00,913 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21038ms.
2019-02-20 03:22:21,953 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 22002ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:22:56,232 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 554ms.
2019-02-20 03:22:56,789 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1840ms.
2019-02-20 03:22:58,631 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2820ms.
2019-02-20 03:23:01,456 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4226ms.
2019-02-20 03:23:05,684 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8471ms.
2019-02-20 03:23:14,158 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12311ms.
2019-02-20 03:23:26,471 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 17159ms.
2019-02-20 03:23:43,633 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15664ms.
2019-02-20 03:23:59,300 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16829ms.
2019-02-20 03:24:16,131 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11365ms.
2019-02-20 03:24:27,499 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8117ms.
2019-02-20 03:24:35,618 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14706ms.
2019-02-20 03:24:50,327 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9868ms.
2019-02-20 03:25:00,198 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18552ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:25:31,010 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 620ms.
2019-02-20 03:25:31,633 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1522ms.
2019-02-20 03:25:33,157 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3700ms.
2019-02-20 03:25:36,863 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6929ms.
2019-02-20 03:25:43,794 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21691ms.
2019-02-20 03:26:05,488 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14867ms.
2019-02-20 03:26:20,358 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18633ms.
2019-02-20 03:26:38,994 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17786ms.
2019-02-20 03:26:56,782 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 8842ms.
2019-02-20 03:27:05,627 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16705ms.
2019-02-20 03:27:22,334 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8283ms.
2019-02-20 03:27:30,620 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14379ms.
2019-02-20 03:27:45,002 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11047ms.
2019-02-20 03:27:56,052 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16305ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:28:24,569 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1233ms.
2019-02-20 03:28:25,805 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1365ms.
2019-02-20 03:28:27,172 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2283ms.
2019-02-20 03:28:29,457 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10651ms.
2019-02-20 03:28:40,113 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15205ms.
2019-02-20 03:28:55,321 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13108ms.
2019-02-20 03:29:08,431 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9752ms.
2019-02-20 03:29:18,185 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13230ms.
2019-02-20 03:29:31,418 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14628ms.
2019-02-20 03:29:46,049 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13618ms.
2019-02-20 03:29:59,669 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16556ms.
2019-02-20 03:30:16,228 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8299ms.
2019-02-20 03:30:24,529 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10305ms.
2019-02-20 03:30:34,837 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13392ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been removed from HDFS
2019-02-20 03:31:00,473 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1469ms.
2019-02-20 03:31:01,944 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2335ms.
2019-02-20 03:31:04,282 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5462ms.
2019-02-20 03:31:09,749 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11615ms.
2019-02-20 03:31:21,366 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13676ms.
2019-02-20 03:31:35,045 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22490ms.
2019-02-20 03:31:57,538 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9993ms.
2019-02-20 03:32:07,533 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11290ms.
2019-02-20 03:32:18,826 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22383ms.
2019-02-20 03:32:41,212 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17910ms.
2019-02-20 03:32:59,124 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16664ms.
2019-02-20 03:33:15,791 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9524ms.
2019-02-20 03:33:25,318 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8331ms.
2019-02-20 03:33:33,651 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21087ms.
put: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-20 03:33:56,860 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 962ms.
2019-02-20 03:33:57,825 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2085ms.
2019-02-20 03:33:59,913 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4025ms.
2019-02-20 03:34:03,943 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8455ms.
2019-02-20 03:34:12,401 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14850ms.
2019-02-20 03:34:27,254 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16990ms.
2019-02-20 03:34:44,247 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18671ms.
2019-02-20 03:35:02,920 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15513ms.
2019-02-20 03:35:18,436 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20148ms.
2019-02-20 03:35:38,587 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22316ms.
2019-02-20 03:36:00,906 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11865ms.
2019-02-20 03:36:12,774 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21478ms.
2019-02-20 03:36:34,254 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8492ms.
2019-02-20 03:36:42,749 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8149ms.
ls: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been put into HDFS
2019-02-20 03:36:53,189 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 604ms.
2019-02-20 03:36:53,795 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2368ms.
2019-02-20 03:36:56,165 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4884ms.
2019-02-20 03:37:01,054 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6941ms.
2019-02-20 03:37:07,997 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 16849ms.
2019-02-20 03:37:24,849 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11862ms.
2019-02-20 03:37:36,714 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16607ms.
2019-02-20 03:37:53,323 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18927ms.
2019-02-20 03:38:12,253 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18256ms.
2019-02-20 03:38:30,512 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22333ms.
2019-02-20 03:38:52,848 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9375ms.
2019-02-20 03:39:02,226 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11318ms.
2019-02-20 03:39:13,546 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10133ms.
2019-02-20 03:39:23,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15685ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:39:51,620 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1166ms.
2019-02-20 03:39:52,789 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1954ms.
2019-02-20 03:39:54,745 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4462ms.
2019-02-20 03:39:59,210 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5373ms.
2019-02-20 03:40:04,588 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14832ms.
2019-02-20 03:40:19,423 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8888ms.
2019-02-20 03:40:28,314 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13855ms.
2019-02-20 03:40:42,171 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20250ms.
2019-02-20 03:41:02,424 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 7784ms.
2019-02-20 03:41:10,210 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15761ms.
2019-02-20 03:41:25,974 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13533ms.
2019-02-20 03:41:39,510 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12319ms.
2019-02-20 03:41:51,831 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9931ms.
2019-02-20 03:42:01,765 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16886ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:42:30,870 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 758ms.
2019-02-20 03:42:31,630 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2378ms.
2019-02-20 03:42:34,011 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3177ms.
2019-02-20 03:42:37,191 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4247ms.
2019-02-20 03:42:41,442 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9375ms.
2019-02-20 03:42:50,820 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12942ms.
2019-02-20 03:43:03,765 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 15408ms.
2019-02-20 03:43:19,175 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7523ms.
2019-02-20 03:43:26,701 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21254ms.
2019-02-20 03:43:47,958 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20883ms.
2019-02-20 03:44:08,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11739ms.
2019-02-20 03:44:20,586 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18088ms.
2019-02-20 03:44:38,677 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21174ms.
2019-02-20 03:44:59,853 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11341ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:45:23,431 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 567ms.
2019-02-20 03:45:24,001 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2713ms.
2019-02-20 03:45:26,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2978ms.
2019-02-20 03:45:29,698 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9452ms.
2019-02-20 03:45:39,153 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15097ms.
2019-02-20 03:45:54,252 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16133ms.
2019-02-20 03:46:10,388 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12624ms.
2019-02-20 03:46:23,015 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12323ms.
2019-02-20 03:46:35,341 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16169ms.
2019-02-20 03:46:51,513 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17394ms.
2019-02-20 03:47:08,909 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14009ms.
2019-02-20 03:47:22,921 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21215ms.
2019-02-20 03:47:44,139 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18203ms.
2019-02-20 03:48:02,345 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12900ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:48:27,480 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 781ms.
2019-02-20 03:48:28,264 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2360ms.
2019-02-20 03:48:30,627 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3920ms.
2019-02-20 03:48:34,552 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8391ms.
2019-02-20 03:48:42,946 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14079ms.
2019-02-20 03:48:57,028 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13788ms.
2019-02-20 03:49:10,819 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18766ms.
2019-02-20 03:49:29,587 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12408ms.
2019-02-20 03:49:41,998 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12138ms.
2019-02-20 03:49:54,139 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17683ms.
2019-02-20 03:50:11,824 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 18774ms.
2019-02-20 03:50:30,601 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13052ms.
2019-02-20 03:50:43,656 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8688ms.
2019-02-20 03:50:52,347 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14861ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:51:19,462 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 999ms.
2019-02-20 03:51:20,464 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1207ms.
2019-02-20 03:51:21,672 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2630ms.
2019-02-20 03:51:24,305 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10181ms.
2019-02-20 03:51:34,491 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15019ms.
2019-02-20 03:51:49,513 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8379ms.
2019-02-20 03:51:57,894 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18730ms.
2019-02-20 03:52:16,627 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20416ms.
2019-02-20 03:52:37,046 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17786ms.
2019-02-20 03:52:54,835 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15663ms.
2019-02-20 03:53:10,501 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10189ms.
2019-02-20 03:53:20,693 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21254ms.
2019-02-20 03:53:41,950 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13367ms.
2019-02-20 03:53:55,319 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14572ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:54:22,157 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1123ms.
2019-02-20 03:54:23,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1534ms.
2019-02-20 03:54:24,819 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2977ms.
2019-02-20 03:54:27,799 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11174ms.
2019-02-20 03:54:38,978 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19902ms.
2019-02-20 03:54:58,883 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9409ms.
2019-02-20 03:55:08,294 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21417ms.
2019-02-20 03:55:29,714 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8239ms.
2019-02-20 03:55:37,955 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11464ms.
2019-02-20 03:55:49,422 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11242ms.
2019-02-20 03:56:00,667 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14210ms.
2019-02-20 03:56:14,880 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11210ms.
2019-02-20 03:56:26,092 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11305ms.
2019-02-20 03:56:37,400 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17286ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 7 signal TERM catched and let quit gracefully
file 10 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-20 03:57:06,928 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 650ms.
2019-02-20 03:57:07,581 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2488ms.
2019-02-20 03:57:10,071 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2362ms.
2019-02-20 03:57:12,438 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7688ms.
2019-02-20 03:57:20,129 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10517ms.
2019-02-20 03:57:30,649 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10347ms.
2019-02-20 03:57:40,999 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19149ms.
2019-02-20 03:58:00,151 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21177ms.
2019-02-20 03:58:21,330 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18852ms.
2019-02-20 03:58:40,185 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10864ms.
2019-02-20 03:58:51,052 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16237ms.
2019-02-20 03:59:07,291 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9219ms.
2019-02-20 03:59:16,512 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21220ms.
2019-02-20 03:59:37,735 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19531ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been removed from HDFS
