Found 20 items
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile10
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile11
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile12
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile13
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile14
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile15
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile16
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile17
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile18
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile19
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile20
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile5
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile6
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile7
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile8
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile9
file 10 has been put into HDFS
file 10 has been read from HDFS for 1 time
diff succeed!
2019-02-27 03:48:00,112 INFO retry.RetryInvocationHandler: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 734ms.
2019-02-27 03:48:00,850 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2021ms.
file 10 has been read from HDFS for 2 time
diff succeed!
file 10 has been read from HDFS for 3 time
diff succeed!
2019-02-27 03:48:45,494 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1109ms.
2019-02-27 03:48:46,606 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1990ms.
2019-02-27 03:48:48,598 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4961ms.
2019-02-27 03:48:53,564 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6690ms.
2019-02-27 03:49:00,349 INFO retry.RetryInvocationHandler: java.io.IOException: DestHost:destPort node-1-link-0:8020 , LocalHost:localPort clnode059.clemson.cloudlab.us/130.127.133.68:0. Failed on local exception: java.io.IOException: Connection reset by peer, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12150ms.
2019-02-27 03:49:12,502 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11049ms.
2019-02-27 03:49:23,553 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16413ms.
2019-02-27 03:49:39,969 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8285ms.
2019-02-27 03:49:48,256 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16635ms.
2019-02-27 03:50:04,893 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12044ms.
2019-02-27 03:50:16,939 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22025ms.
2019-02-27 03:50:38,967 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15435ms.
2019-02-27 03:50:54,404 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11534ms.
2019-02-27 03:51:05,941 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19562ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 03:51:37,820 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1057ms.
2019-02-27 03:51:38,880 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2190ms.
2019-02-27 03:51:41,073 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2193ms.
2019-02-27 03:51:43,271 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6989ms.
2019-02-27 03:51:50,263 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8495ms.
2019-02-27 03:51:58,761 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18586ms.
2019-02-27 03:52:17,350 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11662ms.
2019-02-27 03:52:29,015 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21800ms.
2019-02-27 03:52:50,817 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12874ms.
2019-02-27 03:53:03,694 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8692ms.
2019-02-27 03:53:12,388 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22194ms.
2019-02-27 03:53:34,585 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13768ms.
2019-02-27 03:53:48,355 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 19257ms.
2019-02-27 03:54:07,614 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19500ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 03:54:39,363 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 958ms.
2019-02-27 03:54:40,324 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1227ms.
2019-02-27 03:54:41,554 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2501ms.
2019-02-27 03:54:44,057 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10737ms.
2019-02-27 03:54:54,799 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18403ms.
2019-02-27 03:55:13,205 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 21875ms.
2019-02-27 03:55:35,083 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9224ms.
2019-02-27 03:55:44,309 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9152ms.
2019-02-27 03:55:53,463 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11500ms.
2019-02-27 03:56:04,966 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19258ms.
2019-02-27 03:56:24,226 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9552ms.
2019-02-27 03:56:33,780 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11529ms.
2019-02-27 03:56:45,312 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11860ms.
2019-02-27 03:56:57,174 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18366ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 03:57:27,754 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 738ms.
2019-02-27 03:57:28,495 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2218ms.
2019-02-27 03:57:30,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4245ms.
2019-02-27 03:57:34,963 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7532ms.
2019-02-27 03:57:42,500 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14261ms.
2019-02-27 03:57:56,764 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11444ms.
2019-02-27 03:58:08,211 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10707ms.
2019-02-27 03:58:18,921 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15141ms.
2019-02-27 03:58:34,065 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17976ms.
2019-02-27 03:58:52,044 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20000ms.
2019-02-27 03:59:12,047 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8358ms.
2019-02-27 03:59:20,407 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 20095ms.
2019-02-27 03:59:40,504 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21190ms.
2019-02-27 04:00:01,697 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15800ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:00:29,768 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1088ms.
2019-02-27 04:00:30,859 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2323ms.
2019-02-27 04:00:33,184 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2038ms.
2019-02-27 04:00:35,225 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10427ms.
2019-02-27 04:00:45,658 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9730ms.
2019-02-27 04:00:55,390 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12895ms.
2019-02-27 04:01:08,288 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10871ms.
2019-02-27 04:01:19,162 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19357ms.
2019-02-27 04:01:38,522 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 19755ms.
2019-02-27 04:01:58,280 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15181ms.
2019-02-27 04:02:13,463 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 7820ms.
2019-02-27 04:02:21,286 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 20326ms.
2019-02-27 04:02:41,615 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21119ms.
2019-02-27 04:03:02,737 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12104ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:03:27,075 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 985ms.
2019-02-27 04:03:28,063 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2413ms.
2019-02-27 04:03:30,478 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5162ms.
2019-02-27 04:03:35,646 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9291ms.
2019-02-27 04:03:44,940 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21181ms.
2019-02-27 04:04:06,124 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10996ms.
2019-02-27 04:04:17,123 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19900ms.
2019-02-27 04:04:37,026 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14980ms.
2019-02-27 04:04:52,009 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21460ms.
2019-02-27 04:05:13,471 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18885ms.
2019-02-27 04:05:32,360 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9296ms.
2019-02-27 04:05:41,659 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9646ms.
2019-02-27 04:05:51,308 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12927ms.
2019-02-27 04:06:04,238 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12717ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:06:29,183 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1129ms.
2019-02-27 04:06:30,315 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1655ms.
2019-02-27 04:06:31,972 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4065ms.
2019-02-27 04:06:36,042 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7429ms.
2019-02-27 04:06:43,474 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 16321ms.
2019-02-27 04:06:59,798 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10027ms.
2019-02-27 04:07:09,828 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 15817ms.
2019-02-27 04:07:25,648 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 10369ms.
2019-02-27 04:07:36,019 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21716ms.
2019-02-27 04:07:57,738 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14323ms.
2019-02-27 04:08:12,064 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21444ms.
2019-02-27 04:08:33,511 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9258ms.
2019-02-27 04:08:42,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 22205ms.
2019-02-27 04:09:04,980 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13128ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:09:30,354 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1201ms.
2019-02-27 04:09:31,558 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1705ms.
2019-02-27 04:09:33,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2588ms.
2019-02-27 04:09:35,859 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8154ms.
2019-02-27 04:09:44,016 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17256ms.
2019-02-27 04:10:01,275 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11013ms.
2019-02-27 04:10:12,291 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16604ms.
2019-02-27 04:10:28,898 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19999ms.
2019-02-27 04:10:48,900 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18950ms.
2019-02-27 04:11:07,853 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15375ms.
2019-02-27 04:11:23,231 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10947ms.
2019-02-27 04:11:34,181 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11344ms.
2019-02-27 04:11:45,527 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12327ms.
2019-02-27 04:11:57,858 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16251ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been removed from HDFS
2019-02-27 04:12:26,379 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1366ms.
2019-02-27 04:12:27,748 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2779ms.
2019-02-27 04:12:30,529 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3427ms.
2019-02-27 04:12:33,961 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4245ms.
2019-02-27 04:12:38,209 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17710ms.
2019-02-27 04:12:55,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18097ms.
2019-02-27 04:13:14,022 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10212ms.
2019-02-27 04:13:24,237 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12344ms.
2019-02-27 04:13:36,583 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9919ms.
2019-02-27 04:13:46,505 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22014ms.
2019-02-27 04:14:08,522 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14472ms.
2019-02-27 04:14:22,997 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12000ms.
2019-02-27 04:14:35,000 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12664ms.
2019-02-27 04:14:47,667 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 22200ms.
put: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-27 04:15:11,985 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 854ms.
2019-02-27 04:15:12,843 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2773ms.
2019-02-27 04:15:15,618 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5049ms.
2019-02-27 04:15:20,673 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11772ms.
2019-02-27 04:15:32,448 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9666ms.
2019-02-27 04:15:42,117 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22314ms.
2019-02-27 04:16:04,434 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13459ms.
2019-02-27 04:16:17,896 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14735ms.
2019-02-27 04:16:32,634 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14271ms.
2019-02-27 04:16:46,907 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18408ms.
2019-02-27 04:17:05,318 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22116ms.
2019-02-27 04:17:27,437 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13365ms.
2019-02-27 04:17:40,805 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13115ms.
2019-02-27 04:17:53,923 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8388ms.
ls: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been put into HDFS
2019-02-27 04:18:04,705 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 595ms.
2019-02-27 04:18:05,302 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1344ms.
2019-02-27 04:18:06,648 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3028ms.
2019-02-27 04:18:09,678 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6581ms.
2019-02-27 04:18:16,264 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8241ms.
2019-02-27 04:18:24,508 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17642ms.
2019-02-27 04:18:42,153 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11756ms.
2019-02-27 04:18:53,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7968ms.
2019-02-27 04:19:01,883 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9008ms.
2019-02-27 04:19:10,894 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18765ms.
2019-02-27 04:19:29,661 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10085ms.
2019-02-27 04:19:39,749 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21911ms.
2019-02-27 04:20:01,663 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18630ms.
2019-02-27 04:20:20,296 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12869ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:20:45,405 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 559ms.
2019-02-27 04:20:45,966 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2383ms.
2019-02-27 04:20:48,352 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2464ms.
2019-02-27 04:20:50,822 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5078ms.
2019-02-27 04:20:55,903 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 16697ms.
2019-02-27 04:21:12,603 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10771ms.
2019-02-27 04:21:23,377 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12549ms.
2019-02-27 04:21:35,929 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19527ms.
2019-02-27 04:21:55,459 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 8702ms.
2019-02-27 04:22:04,164 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17656ms.
2019-02-27 04:22:21,823 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21689ms.
2019-02-27 04:22:43,515 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15935ms.
2019-02-27 04:22:59,452 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15898ms.
2019-02-27 04:23:15,353 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 10164ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:23:37,754 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1075ms.
2019-02-27 04:23:38,832 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2320ms.
2019-02-27 04:23:41,154 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5360ms.
2019-02-27 04:23:46,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8198ms.
2019-02-27 04:23:54,721 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10432ms.
2019-02-27 04:24:05,155 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17747ms.
2019-02-27 04:24:22,905 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21184ms.
2019-02-27 04:24:44,092 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20927ms.
2019-02-27 04:25:05,022 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22242ms.
2019-02-27 04:25:27,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11635ms.
2019-02-27 04:25:38,904 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16297ms.
2019-02-27 04:25:55,203 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18988ms.
2019-02-27 04:26:14,194 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10497ms.
2019-02-27 04:26:24,694 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9486ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:26:46,473 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 539ms.
2019-02-27 04:26:47,015 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1433ms.
2019-02-27 04:26:48,450 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5724ms.
2019-02-27 04:26:54,176 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8923ms.
2019-02-27 04:27:03,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19908ms.
2019-02-27 04:27:23,015 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19014ms.
2019-02-27 04:27:42,032 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 7651ms.
2019-02-27 04:27:49,685 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18690ms.
2019-02-27 04:28:08,378 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12780ms.
2019-02-27 04:28:21,161 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15361ms.
2019-02-27 04:28:36,524 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11218ms.
2019-02-27 04:28:47,744 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14078ms.
2019-02-27 04:29:01,826 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9621ms.
2019-02-27 04:29:11,450 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14893ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:29:38,571 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1024ms.
2019-02-27 04:29:39,597 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2478ms.
2019-02-27 04:29:42,078 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3901ms.
2019-02-27 04:29:45,985 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7723ms.
2019-02-27 04:29:53,711 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19051ms.
2019-02-27 04:30:12,765 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18155ms.
2019-02-27 04:30:30,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16381ms.
2019-02-27 04:30:47,306 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 10418ms.
2019-02-27 04:30:57,727 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17333ms.
2019-02-27 04:31:15,063 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17955ms.
2019-02-27 04:31:33,021 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20417ms.
2019-02-27 04:31:53,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9815ms.
2019-02-27 04:32:03,258 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11237ms.
2019-02-27 04:32:14,498 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16746ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 5 signal TERM catched and let quit gracefully
file 10 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile10: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile10': No such file or directory
2019-02-27 04:32:43,487 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 864ms.
2019-02-27 04:32:44,354 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1831ms.
2019-02-27 04:32:46,187 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5343ms.
2019-02-27 04:32:51,536 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5422ms.
2019-02-27 04:32:56,960 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19284ms.
2019-02-27 04:33:16,247 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17259ms.
2019-02-27 04:33:33,509 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10749ms.
2019-02-27 04:33:44,261 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9734ms.
2019-02-27 04:33:53,998 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11549ms.
2019-02-27 04:34:05,549 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21727ms.
2019-02-27 04:34:27,279 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9315ms.
2019-02-27 04:34:36,597 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21602ms.
2019-02-27 04:34:58,202 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21920ms.
2019-02-27 04:35:20,125 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9221ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 10 has been removed from HDFS
