Found 20 items
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile10
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile11._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile12._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile13._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile14
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile15
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile16
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile17
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile18
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile19._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile20
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile4
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile5._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile6
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile7
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile8
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile9
file 14 has been put into HDFS
file 14 has been read from HDFS for 1 time
diff succeed!
file 14 has been read from HDFS for 2 time
diff succeed!
file 14 has been read from HDFS for 3 time
diff succeed!
file 14 has been read from HDFS for 4 time
diff succeed!
2019-02-20 03:10:56,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1138ms.
2019-02-20 03:10:57,823 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1916ms.
2019-02-20 03:10:59,742 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2708ms.
2019-02-20 03:11:02,452 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8775ms.
2019-02-20 03:11:11,231 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17433ms.
2019-02-20 03:11:28,667 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 21263ms.
2019-02-20 03:11:49,933 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8565ms.
2019-02-20 03:11:58,500 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9704ms.
2019-02-20 03:12:08,206 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16229ms.
2019-02-20 03:12:24,437 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20075ms.
2019-02-20 03:12:44,515 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19757ms.
2019-02-20 03:13:04,274 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17091ms.
2019-02-20 03:13:21,368 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20785ms.
2019-02-20 03:13:42,155 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 10820ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:14:05,204 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1290ms.
2019-02-20 03:14:06,497 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2279ms.
2019-02-20 03:14:08,778 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5333ms.
2019-02-20 03:14:14,116 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6312ms.
2019-02-20 03:14:20,431 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9497ms.
2019-02-20 03:14:29,930 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 7808ms.
2019-02-20 03:14:37,741 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18781ms.
2019-02-20 03:14:56,524 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18022ms.
2019-02-20 03:15:14,549 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11599ms.
2019-02-20 03:15:26,150 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19288ms.
2019-02-20 03:15:45,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16383ms.
2019-02-20 03:16:01,826 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10700ms.
2019-02-20 03:16:12,529 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12283ms.
2019-02-20 03:16:24,814 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8940ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:16:46,027 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1213ms.
2019-02-20 03:16:47,242 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1623ms.
2019-02-20 03:16:48,873 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5587ms.
2019-02-20 03:16:54,465 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10488ms.
2019-02-20 03:17:04,956 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9038ms.
2019-02-20 03:17:13,997 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16941ms.
2019-02-20 03:17:30,941 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16856ms.
2019-02-20 03:17:47,799 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 10803ms.
2019-02-20 03:17:58,604 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20738ms.
2019-02-20 03:18:19,345 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8497ms.
2019-02-20 03:18:27,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15811ms.
2019-02-20 03:18:43,657 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15173ms.
2019-02-20 03:18:58,833 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13207ms.
2019-02-20 03:19:12,042 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13791ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:19:38,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 683ms.
2019-02-20 03:19:38,754 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1151ms.
2019-02-20 03:19:39,907 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3017ms.
2019-02-20 03:19:42,926 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5890ms.
2019-02-20 03:19:48,822 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20852ms.
2019-02-20 03:20:09,677 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8994ms.
2019-02-20 03:20:18,674 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13635ms.
2019-02-20 03:20:32,311 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12459ms.
2019-02-20 03:20:44,773 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16423ms.
2019-02-20 03:21:01,198 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18674ms.
2019-02-20 03:21:19,875 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12781ms.
2019-02-20 03:21:32,658 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17554ms.
2019-02-20 03:21:50,215 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8142ms.
2019-02-20 03:21:58,359 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18156ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:22:28,741 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1473ms.
2019-02-20 03:22:30,217 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1096ms.
2019-02-20 03:22:31,314 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5632ms.
2019-02-20 03:22:36,949 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5222ms.
2019-02-20 03:22:42,176 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19808ms.
2019-02-20 03:23:01,987 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12924ms.
2019-02-20 03:23:14,914 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12750ms.
2019-02-20 03:23:27,666 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17389ms.
2019-02-20 03:23:45,058 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20054ms.
2019-02-20 03:24:05,115 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15030ms.
2019-02-20 03:24:20,147 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 18098ms.
2019-02-20 03:24:38,248 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21244ms.
2019-02-20 03:24:59,495 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11756ms.
2019-02-20 03:25:11,254 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8076ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:25:31,574 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1168ms.
2019-02-20 03:25:32,745 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1497ms.
2019-02-20 03:25:34,244 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2502ms.
2019-02-20 03:25:36,750 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4490ms.
2019-02-20 03:25:41,243 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19553ms.
2019-02-20 03:26:00,798 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17068ms.
2019-02-20 03:26:17,869 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 17975ms.
2019-02-20 03:26:35,847 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17569ms.
2019-02-20 03:26:53,419 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14392ms.
2019-02-20 03:27:07,813 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13591ms.
2019-02-20 03:27:21,407 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13246ms.
2019-02-20 03:27:34,655 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12067ms.
2019-02-20 03:27:46,725 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14732ms.
2019-02-20 03:28:01,459 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16646ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:28:30,317 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1135ms.
2019-02-20 03:28:31,455 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1767ms.
2019-02-20 03:28:33,224 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4530ms.
2019-02-20 03:28:37,757 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5430ms.
2019-02-20 03:28:43,192 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9202ms.
2019-02-20 03:28:52,397 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16027ms.
2019-02-20 03:29:08,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13033ms.
2019-02-20 03:29:21,463 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8021ms.
2019-02-20 03:29:29,487 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12418ms.
2019-02-20 03:29:41,908 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21410ms.
2019-02-20 03:30:03,321 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21952ms.
2019-02-20 03:30:25,275 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14340ms.
2019-02-20 03:30:39,618 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8842ms.
2019-02-20 03:30:48,463 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14994ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been removed from HDFS
2019-02-20 03:31:15,679 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 970ms.
2019-02-20 03:31:16,651 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2842ms.
2019-02-20 03:31:19,496 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3669ms.
2019-02-20 03:31:23,170 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4240ms.
2019-02-20 03:31:27,412 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21012ms.
2019-02-20 03:31:48,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9721ms.
2019-02-20 03:31:58,151 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11944ms.
2019-02-20 03:32:10,097 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15140ms.
2019-02-20 03:32:25,240 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12867ms.
2019-02-20 03:32:38,110 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17539ms.
2019-02-20 03:32:55,652 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22085ms.
2019-02-20 03:33:17,740 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17765ms.
2019-02-20 03:33:35,508 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16951ms.
2019-02-20 03:33:52,462 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18039ms.
put: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-20 03:34:12,620 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1299ms.
2019-02-20 03:34:13,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2848ms.
2019-02-20 03:34:16,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3281ms.
2019-02-20 03:34:20,058 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6000ms.
2019-02-20 03:34:26,061 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17149ms.
2019-02-20 03:34:43,213 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15352ms.
2019-02-20 03:34:58,568 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21145ms.
2019-02-20 03:35:19,716 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20521ms.
2019-02-20 03:35:40,239 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22031ms.
2019-02-20 03:36:02,273 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20005ms.
2019-02-20 03:36:22,281 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10316ms.
2019-02-20 03:36:32,599 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14881ms.
2019-02-20 03:36:47,483 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16011ms.
2019-02-20 03:37:03,497 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19813ms.
ls: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been put into HDFS
2019-02-20 03:37:25,585 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1185ms.
2019-02-20 03:37:26,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1491ms.
2019-02-20 03:37:28,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4172ms.
2019-02-20 03:37:32,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9141ms.
2019-02-20 03:37:41,587 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12035ms.
2019-02-20 03:37:53,624 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8797ms.
2019-02-20 03:38:02,424 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18053ms.
2019-02-20 03:38:20,480 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 16046ms.
2019-02-20 03:38:36,529 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16537ms.
2019-02-20 03:38:53,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20891ms.
2019-02-20 03:39:13,962 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12423ms.
2019-02-20 03:39:26,388 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11454ms.
2019-02-20 03:39:37,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15863ms.
2019-02-20 03:39:53,710 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18996ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:40:24,945 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1032ms.
2019-02-20 03:40:25,980 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2520ms.
2019-02-20 03:40:28,503 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4317ms.
2019-02-20 03:40:32,824 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7947ms.
2019-02-20 03:40:40,773 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19546ms.
2019-02-20 03:41:00,322 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19128ms.
2019-02-20 03:41:19,453 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 20551ms.
2019-02-20 03:41:40,007 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9128ms.
2019-02-20 03:41:49,137 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9319ms.
2019-02-20 03:41:58,458 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17254ms.
2019-02-20 03:42:15,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20894ms.
2019-02-20 03:42:36,612 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 20153ms.
2019-02-20 03:42:56,768 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18607ms.
2019-02-20 03:43:15,377 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12445ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:43:40,055 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1412ms.
2019-02-20 03:43:41,469 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2720ms.
2019-02-20 03:43:44,191 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2941ms.
2019-02-20 03:43:47,137 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11105ms.
2019-02-20 03:43:58,244 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 22435ms.
2019-02-20 03:44:20,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15307ms.
2019-02-20 03:44:35,992 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12523ms.
2019-02-20 03:44:48,517 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15827ms.
2019-02-20 03:45:04,347 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17290ms.
2019-02-20 03:45:21,640 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12664ms.
2019-02-20 03:45:34,307 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14527ms.
2019-02-20 03:45:48,836 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17619ms.
2019-02-20 03:46:06,458 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10323ms.
2019-02-20 03:46:16,784 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16904ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:46:45,924 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 636ms.
2019-02-20 03:46:46,562 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1083ms.
2019-02-20 03:46:47,647 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3079ms.
2019-02-20 03:46:50,729 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10156ms.
2019-02-20 03:47:00,890 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10116ms.
2019-02-20 03:47:11,008 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17408ms.
2019-02-20 03:47:28,419 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 15562ms.
2019-02-20 03:47:43,984 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15427ms.
2019-02-20 03:47:59,414 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 7768ms.
2019-02-20 03:48:07,184 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17101ms.
2019-02-20 03:48:24,288 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22280ms.
2019-02-20 03:48:46,571 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18642ms.
2019-02-20 03:49:05,216 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16337ms.
2019-02-20 03:49:21,556 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21409ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:49:55,228 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1184ms.
2019-02-20 03:49:56,415 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2798ms.
2019-02-20 03:49:59,215 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4927ms.
2019-02-20 03:50:04,148 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7922ms.
2019-02-20 03:50:12,072 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9851ms.
2019-02-20 03:50:21,926 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15277ms.
2019-02-20 03:50:37,205 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13813ms.
2019-02-20 03:50:51,021 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21889ms.
2019-02-20 03:51:12,913 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17261ms.
2019-02-20 03:51:30,177 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20488ms.
2019-02-20 03:51:50,668 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 17011ms.
2019-02-20 03:52:07,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21156ms.
2019-02-20 03:52:28,841 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 17809ms.
2019-02-20 03:52:46,653 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12748ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:53:11,644 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1292ms.
2019-02-20 03:53:12,939 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1463ms.
2019-02-20 03:53:14,404 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3469ms.
2019-02-20 03:53:17,875 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9727ms.
2019-02-20 03:53:27,607 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 16651ms.
2019-02-20 03:53:44,261 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13015ms.
2019-02-20 03:53:57,279 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21742ms.
2019-02-20 03:54:19,024 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18214ms.
2019-02-20 03:54:37,241 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21186ms.
2019-02-20 03:54:58,429 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21439ms.
2019-02-20 03:55:19,871 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11080ms.
2019-02-20 03:55:30,954 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21384ms.
2019-02-20 03:55:52,341 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11880ms.
2019-02-20 03:56:04,224 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17125ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 6 signal TERM catched and let quit gracefully
file 14 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile14: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile14': No such file or directory
2019-02-20 03:56:33,571 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1222ms.
2019-02-20 03:56:34,795 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1888ms.
2019-02-20 03:56:36,686 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2340ms.
2019-02-20 03:56:39,031 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6166ms.
2019-02-20 03:56:45,200 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20714ms.
2019-02-20 03:57:05,917 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10468ms.
2019-02-20 03:57:16,388 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11346ms.
2019-02-20 03:57:27,737 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 22064ms.
2019-02-20 03:57:49,803 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14516ms.
2019-02-20 03:58:04,322 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22034ms.
2019-02-20 03:58:26,359 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9416ms.
2019-02-20 03:58:35,778 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8961ms.
2019-02-20 03:58:44,742 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14823ms.
2019-02-20 03:58:59,567 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16834ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 14 has been removed from HDFS
