Found 20 items
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile1._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile10
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile11._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile12._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile13
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile14._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile15._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile16._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile17._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile18._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile19._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile2
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile20._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile3._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile5
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile6._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 02:03 /myfile7
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile8._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 02:02 /myfile9._COPYING_
file 13 has been put into HDFS
file 13 has been read from HDFS for 1 time
diff succeed!
file 13 has been read from HDFS for 2 time
diff succeed!
2019-02-27 02:04:36,196 INFO retry.RetryInvocationHandler: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 760ms.
2019-02-27 02:04:36,959 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2083ms.
2019-02-27 02:04:39,044 INFO retry.RetryInvocationHandler: java.io.EOFException: End of File Exception between local host is: "clnode059.clemson.cloudlab.us/130.127.133.68"; destination host is: "node-1-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5867ms.
2019-02-27 02:04:44,914 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10243ms.
2019-02-27 02:04:55,163 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 11675ms.
2019-02-27 02:05:06,841 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9067ms.
2019-02-27 02:05:15,910 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11900ms.
2019-02-27 02:05:27,812 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18240ms.
2019-02-27 02:05:46,055 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14708ms.
2019-02-27 02:06:00,765 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22122ms.
2019-02-27 02:06:22,890 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20926ms.
2019-02-27 02:06:43,818 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11375ms.
2019-02-27 02:06:55,195 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15353ms.
2019-02-27 02:07:10,551 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16283ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:07:39,082 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1260ms.
2019-02-27 02:07:40,345 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1533ms.
2019-02-27 02:07:41,880 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5806ms.
2019-02-27 02:07:47,689 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10831ms.
2019-02-27 02:07:58,525 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21604ms.
2019-02-27 02:08:20,132 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16400ms.
2019-02-27 02:08:36,534 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11150ms.
2019-02-27 02:08:47,686 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 16251ms.
2019-02-27 02:09:03,940 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17138ms.
2019-02-27 02:09:21,080 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 9165ms.
2019-02-27 02:09:30,247 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8621ms.
2019-02-27 02:09:38,871 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19984ms.
2019-02-27 02:09:58,857 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 22415ms.
2019-02-27 02:10:21,275 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12768ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:10:46,271 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1422ms.
2019-02-27 02:10:47,696 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2448ms.
2019-02-27 02:10:50,147 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4838ms.
2019-02-27 02:10:54,990 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6390ms.
2019-02-27 02:11:01,383 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8368ms.
2019-02-27 02:11:09,754 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19973ms.
2019-02-27 02:11:29,730 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10040ms.
2019-02-27 02:11:39,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17100ms.
2019-02-27 02:11:56,875 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14966ms.
2019-02-27 02:12:11,843 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17700ms.
2019-02-27 02:12:29,546 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15853ms.
2019-02-27 02:12:45,401 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15495ms.
2019-02-27 02:13:00,899 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21755ms.
2019-02-27 02:13:22,657 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 7539ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:13:42,400 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1331ms.
2019-02-27 02:13:43,734 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2510ms.
2019-02-27 02:13:46,246 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2198ms.
2019-02-27 02:13:48,448 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9178ms.
2019-02-27 02:13:57,629 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12439ms.
2019-02-27 02:14:10,071 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11981ms.
2019-02-27 02:14:22,055 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12663ms.
2019-02-27 02:14:34,720 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14020ms.
2019-02-27 02:14:48,742 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10471ms.
2019-02-27 02:14:59,216 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10527ms.
2019-02-27 02:15:09,745 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 17919ms.
2019-02-27 02:15:27,666 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10669ms.
2019-02-27 02:15:38,338 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15729ms.
2019-02-27 02:15:54,069 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21979ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:16:28,259 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 779ms.
2019-02-27 02:16:29,040 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2939ms.
2019-02-27 02:16:31,982 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5003ms.
2019-02-27 02:16:36,991 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11072ms.
2019-02-27 02:16:48,066 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17963ms.
2019-02-27 02:17:06,031 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11493ms.
2019-02-27 02:17:17,527 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12249ms.
2019-02-27 02:17:29,779 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 22080ms.
2019-02-27 02:17:51,861 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17574ms.
2019-02-27 02:18:09,438 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11724ms.
2019-02-27 02:18:21,164 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21876ms.
2019-02-27 02:18:43,043 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11967ms.
2019-02-27 02:18:55,013 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20824ms.
2019-02-27 02:19:15,840 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9973ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:19:38,039 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 511ms.
2019-02-27 02:19:38,553 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2239ms.
2019-02-27 02:19:40,794 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5510ms.
2019-02-27 02:19:46,309 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10024ms.
2019-02-27 02:19:56,336 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15620ms.
2019-02-27 02:20:11,959 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10291ms.
2019-02-27 02:20:22,252 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 14265ms.
2019-02-27 02:20:36,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15621ms.
2019-02-27 02:20:52,143 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20925ms.
2019-02-27 02:21:13,070 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19170ms.
2019-02-27 02:21:32,243 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11877ms.
2019-02-27 02:21:44,122 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9745ms.
2019-02-27 02:21:53,869 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 22411ms.
2019-02-27 02:22:16,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16800ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:22:45,333 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 984ms.
2019-02-27 02:22:46,320 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2094ms.
2019-02-27 02:22:48,416 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2649ms.
2019-02-27 02:22:51,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10472ms.
2019-02-27 02:23:01,544 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18390ms.
2019-02-27 02:23:19,937 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 21299ms.
2019-02-27 02:23:41,239 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10078ms.
2019-02-27 02:23:51,319 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12130ms.
2019-02-27 02:24:03,451 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 8137ms.
2019-02-27 02:24:11,591 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13274ms.
2019-02-27 02:24:24,867 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13820ms.
2019-02-27 02:24:38,689 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22214ms.
2019-02-27 02:25:00,906 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11159ms.
2019-02-27 02:25:12,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16284ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:25:40,550 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 607ms.
2019-02-27 02:25:41,160 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1573ms.
2019-02-27 02:25:42,735 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5192ms.
2019-02-27 02:25:47,933 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7993ms.
2019-02-27 02:25:55,928 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15812ms.
2019-02-27 02:26:11,743 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13594ms.
2019-02-27 02:26:25,340 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10245ms.
2019-02-27 02:26:35,587 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14711ms.
2019-02-27 02:26:50,300 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14378ms.
2019-02-27 02:27:04,681 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19385ms.
2019-02-27 02:27:24,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16519ms.
2019-02-27 02:27:40,590 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10769ms.
2019-02-27 02:27:51,362 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20739ms.
2019-02-27 02:28:12,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 20573ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:28:44,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 763ms.
2019-02-27 02:28:45,678 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1255ms.
2019-02-27 02:28:46,935 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4126ms.
2019-02-27 02:28:51,067 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4096ms.
2019-02-27 02:28:55,165 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13299ms.
2019-02-27 02:29:08,467 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22306ms.
2019-02-27 02:29:30,776 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19883ms.
2019-02-27 02:29:50,661 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21853ms.
2019-02-27 02:30:12,517 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20257ms.
2019-02-27 02:30:32,777 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19760ms.
2019-02-27 02:30:52,540 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21076ms.
2019-02-27 02:31:13,619 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11243ms.
2019-02-27 02:31:24,865 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 22370ms.
2019-02-27 02:31:47,238 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12828ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been removed from HDFS
2019-02-27 02:32:12,270 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 961ms.
2019-02-27 02:32:13,233 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1212ms.
2019-02-27 02:32:14,447 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5864ms.
2019-02-27 02:32:20,316 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6698ms.
2019-02-27 02:32:27,016 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21863ms.
2019-02-27 02:32:48,882 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 7972ms.
2019-02-27 02:32:56,856 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12373ms.
2019-02-27 02:33:09,231 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18903ms.
2019-02-27 02:33:28,137 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 19056ms.
2019-02-27 02:33:47,196 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18937ms.
2019-02-27 02:34:06,136 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 18398ms.
2019-02-27 02:34:24,536 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10280ms.
2019-02-27 02:34:34,819 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13963ms.
2019-02-27 02:34:48,785 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19783ms.
put: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-27 02:35:10,695 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1067ms.
2019-02-27 02:35:11,764 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2241ms.
2019-02-27 02:35:14,008 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4725ms.
2019-02-27 02:35:18,737 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8656ms.
2019-02-27 02:35:27,396 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8355ms.
2019-02-27 02:35:35,753 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10661ms.
2019-02-27 02:35:46,417 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 14114ms.
2019-02-27 02:36:00,533 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13453ms.
2019-02-27 02:36:13,989 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16634ms.
2019-02-27 02:36:30,626 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21788ms.
2019-02-27 02:36:52,417 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9020ms.
2019-02-27 02:37:01,440 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14844ms.
2019-02-27 02:37:16,286 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 19094ms.
2019-02-27 02:37:35,383 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15801ms.
ls: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been put into HDFS
2019-02-27 02:37:53,591 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 810ms.
2019-02-27 02:37:54,403 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2159ms.
2019-02-27 02:37:56,564 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3811ms.
2019-02-27 02:38:00,380 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11497ms.
2019-02-27 02:38:11,879 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21756ms.
2019-02-27 02:38:33,638 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17912ms.
2019-02-27 02:38:51,553 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10843ms.
2019-02-27 02:39:02,399 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11825ms.
2019-02-27 02:39:14,226 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10485ms.
2019-02-27 02:39:24,714 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18456ms.
2019-02-27 02:39:43,173 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14693ms.
2019-02-27 02:39:57,869 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14991ms.
2019-02-27 02:40:12,862 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14807ms.
2019-02-27 02:40:27,672 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13116ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:40:53,063 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 553ms.
2019-02-27 02:40:53,619 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2357ms.
2019-02-27 02:40:55,978 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5874ms.
2019-02-27 02:41:01,857 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11580ms.
2019-02-27 02:41:13,440 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12441ms.
2019-02-27 02:41:25,883 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19205ms.
2019-02-27 02:41:45,091 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11835ms.
2019-02-27 02:41:56,929 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15906ms.
2019-02-27 02:42:12,838 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 15838ms.
2019-02-27 02:42:28,678 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7622ms.
2019-02-27 02:42:36,303 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19904ms.
2019-02-27 02:42:56,209 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21830ms.
2019-02-27 02:43:18,042 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8757ms.
2019-02-27 02:43:26,801 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9099ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:43:48,125 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 950ms.
2019-02-27 02:43:49,077 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2473ms.
2019-02-27 02:43:51,553 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3543ms.
2019-02-27 02:43:55,101 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10228ms.
2019-02-27 02:44:05,332 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19472ms.
2019-02-27 02:44:24,806 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 21900ms.
2019-02-27 02:44:46,709 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12228ms.
2019-02-27 02:44:58,941 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21999ms.
2019-02-27 02:45:20,943 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 13236ms.
2019-02-27 02:45:34,182 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20598ms.
2019-02-27 02:45:54,782 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8813ms.
2019-02-27 02:46:03,598 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14490ms.
2019-02-27 02:46:18,091 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18225ms.
2019-02-27 02:46:36,318 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18087ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:47:06,661 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1350ms.
2019-02-27 02:47:08,014 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1078ms.
2019-02-27 02:47:09,094 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2379ms.
2019-02-27 02:47:11,475 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5483ms.
2019-02-27 02:47:16,963 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13010ms.
2019-02-27 02:47:29,976 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8442ms.
2019-02-27 02:47:38,420 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9717ms.
2019-02-27 02:47:48,140 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7811ms.
2019-02-27 02:47:55,954 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16821ms.
2019-02-27 02:48:12,778 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12476ms.
2019-02-27 02:48:25,257 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21610ms.
2019-02-27 02:48:46,870 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12538ms.
2019-02-27 02:48:59,410 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9955ms.
2019-02-27 02:49:09,368 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16643ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 4 signal TERM catched and let quit gracefully
file 13 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile13: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile13': No such file or directory
2019-02-27 02:49:38,256 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1324ms.
2019-02-27 02:49:39,583 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1064ms.
2019-02-27 02:49:40,649 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2043ms.
2019-02-27 02:49:42,693 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10977ms.
2019-02-27 02:49:53,675 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20085ms.
2019-02-27 02:50:13,763 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9255ms.
2019-02-27 02:50:23,021 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22410ms.
2019-02-27 02:50:45,434 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13038ms.
2019-02-27 02:50:58,475 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17226ms.
2019-02-27 02:51:15,703 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21362ms.
2019-02-27 02:51:37,068 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19525ms.
2019-02-27 02:51:56,596 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22004ms.
2019-02-27 02:52:18,603 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 7892ms.
2019-02-27 02:52:26,497 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 22387ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 13 has been removed from HDFS
