Found 20 items
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile1._COPYING_
-rw-r--r--   3 root supergroup  671088640 2019-02-21 16:11 /myfile10._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile11._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile12._COPYING_
-rw-r--r--   3 root supergroup  805306368 2019-02-21 16:11 /myfile13._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile14._COPYING_
-rw-r--r--   3 root supergroup  805306368 2019-02-21 16:11 /myfile15._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile16._COPYING_
-rw-r--r--   3 root supergroup  805306368 2019-02-21 16:11 /myfile17._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile18._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-21 16:11 /myfile19
-rw-r--r--   3 root supergroup 1073741824 2019-02-21 16:11 /myfile2
-rw-r--r--   3 root supergroup  805306368 2019-02-21 16:11 /myfile20._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-21 16:11 /myfile3
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile4._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile5._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile6._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile7._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile8._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-21 16:11 /myfile9._COPYING_
file 2 has been put into HDFS
file 2 has been read from HDFS for 1 time
diff succeed!
file 2 has been read from HDFS for 2 time
diff succeed!
file 2 has been read from HDFS for 3 time
diff succeed!
file 2 has been read from HDFS for 4 time
diff succeed!
2019-02-21 16:13:24,611 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1415ms.
2019-02-21 16:13:26,029 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2765ms.
2019-02-21 16:13:28,796 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3288ms.
2019-02-21 16:13:32,089 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9596ms.
2019-02-21 16:13:41,688 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9685ms.
2019-02-21 16:13:51,375 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10144ms.
2019-02-21 16:14:01,522 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8743ms.
2019-02-21 16:14:10,267 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17328ms.
2019-02-21 16:14:27,597 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20518ms.
2019-02-21 16:14:48,118 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11687ms.
2019-02-21 16:14:59,807 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21126ms.
2019-02-21 16:15:20,935 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17372ms.
2019-02-21 16:15:38,310 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 19985ms.
2019-02-21 16:15:58,298 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21327ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:16:31,923 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1299ms.
2019-02-21 16:16:33,226 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1815ms.
2019-02-21 16:16:35,042 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4044ms.
2019-02-21 16:16:39,089 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11653ms.
2019-02-21 16:16:50,747 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9906ms.
2019-02-21 16:17:00,655 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 21913ms.
2019-02-21 16:17:22,571 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11401ms.
2019-02-21 16:17:33,974 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21053ms.
2019-02-21 16:17:55,029 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 7547ms.
2019-02-21 16:18:02,578 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14687ms.
2019-02-21 16:18:17,268 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8153ms.
2019-02-21 16:18:25,423 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18188ms.
2019-02-21 16:18:43,614 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13487ms.
2019-02-21 16:18:57,103 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18880ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:19:28,329 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 688ms.
2019-02-21 16:19:29,020 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1342ms.
2019-02-21 16:19:30,364 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2618ms.
2019-02-21 16:19:32,984 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11745ms.
2019-02-21 16:19:44,733 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21714ms.
2019-02-21 16:20:06,450 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14500ms.
2019-02-21 16:20:20,953 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11751ms.
2019-02-21 16:20:32,706 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20935ms.
2019-02-21 16:20:53,644 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 19851ms.
2019-02-21 16:21:13,497 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12504ms.
2019-02-21 16:21:26,004 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10069ms.
2019-02-21 16:21:36,076 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8060ms.
2019-02-21 16:21:44,138 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 7800ms.
2019-02-21 16:21:51,941 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8310ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:22:12,468 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1140ms.
2019-02-21 16:22:13,611 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2408ms.
2019-02-21 16:22:16,021 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5760ms.
2019-02-21 16:22:21,787 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8770ms.
2019-02-21 16:22:30,560 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12153ms.
2019-02-21 16:22:42,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9673ms.
2019-02-21 16:22:52,391 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8606ms.
2019-02-21 16:23:01,000 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9059ms.
2019-02-21 16:23:10,061 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22125ms.
2019-02-21 16:23:32,189 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20289ms.
2019-02-21 16:23:52,480 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20552ms.
2019-02-21 16:24:13,035 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14695ms.
2019-02-21 16:24:27,732 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9927ms.
2019-02-21 16:24:37,662 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21883ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:25:11,829 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1345ms.
2019-02-21 16:25:13,177 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1035ms.
2019-02-21 16:25:14,214 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4451ms.
2019-02-21 16:25:18,670 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10723ms.
2019-02-21 16:25:29,396 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15680ms.
2019-02-21 16:25:45,079 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13556ms.
2019-02-21 16:25:58,637 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19839ms.
2019-02-21 16:26:18,479 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11636ms.
2019-02-21 16:26:30,117 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14540ms.
2019-02-21 16:26:44,659 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8034ms.
2019-02-21 16:26:52,695 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19664ms.
2019-02-21 16:27:12,362 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13832ms.
2019-02-21 16:27:26,197 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10933ms.
2019-02-21 16:27:37,133 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15547ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:28:04,888 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 806ms.
2019-02-21 16:28:05,696 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1406ms.
2019-02-21 16:28:07,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4650ms.
2019-02-21 16:28:11,759 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6928ms.
2019-02-21 16:28:18,690 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19458ms.
2019-02-21 16:28:38,151 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8949ms.
2019-02-21 16:28:47,103 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9218ms.
2019-02-21 16:28:56,323 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11808ms.
2019-02-21 16:29:08,134 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17886ms.
2019-02-21 16:29:26,023 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12580ms.
2019-02-21 16:29:38,605 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13286ms.
2019-02-21 16:29:51,894 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8476ms.
2019-02-21 16:30:00,372 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9764ms.
2019-02-21 16:30:10,139 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16741ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:30:39,144 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 720ms.
2019-02-21 16:30:39,866 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1712ms.
2019-02-21 16:30:41,580 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3127ms.
2019-02-21 16:30:44,712 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5951ms.
2019-02-21 16:30:50,665 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17677ms.
2019-02-21 16:31:08,345 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18759ms.
2019-02-21 16:31:27,107 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 20280ms.
2019-02-21 16:31:47,389 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17918ms.
2019-02-21 16:32:05,310 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22050ms.
2019-02-21 16:32:27,363 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13257ms.
2019-02-21 16:32:40,622 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11089ms.
2019-02-21 16:32:51,713 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12765ms.
2019-02-21 16:33:04,481 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20190ms.
2019-02-21 16:33:24,674 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18428ms.
rm: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been removed from HDFS
2019-02-21 16:33:55,354 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 963ms.
2019-02-21 16:33:56,320 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2662ms.
2019-02-21 16:33:58,985 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5920ms.
2019-02-21 16:34:04,907 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8201ms.
2019-02-21 16:34:13,113 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 22157ms.
2019-02-21 16:34:35,273 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18735ms.
2019-02-21 16:34:54,011 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22005ms.
2019-02-21 16:35:16,019 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20786ms.
2019-02-21 16:35:36,808 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 13477ms.
2019-02-21 16:35:50,287 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14911ms.
2019-02-21 16:36:05,201 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12857ms.
2019-02-21 16:36:18,061 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 16980ms.
2019-02-21 16:36:35,043 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15049ms.
2019-02-21 16:36:50,095 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16320ms.
put: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-21 16:37:08,557 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 978ms.
2019-02-21 16:37:09,538 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1653ms.
2019-02-21 16:37:11,194 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2874ms.
2019-02-21 16:37:14,073 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6393ms.
2019-02-21 16:37:20,468 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8131ms.
2019-02-21 16:37:28,601 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12035ms.
2019-02-21 16:37:40,639 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8196ms.
2019-02-21 16:37:48,838 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20696ms.
2019-02-21 16:38:09,537 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11866ms.
2019-02-21 16:38:21,405 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22409ms.
2019-02-21 16:38:43,817 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11903ms.
2019-02-21 16:38:55,723 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 20709ms.
2019-02-21 16:39:16,434 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15109ms.
2019-02-21 16:39:31,546 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11596ms.
ls: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been put into HDFS
2019-02-21 16:39:45,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 547ms.
2019-02-21 16:39:45,990 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2093ms.
2019-02-21 16:39:48,086 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2227ms.
2019-02-21 16:39:50,315 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11440ms.
2019-02-21 16:40:01,760 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14860ms.
2019-02-21 16:40:16,623 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14915ms.
2019-02-21 16:40:31,541 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 20645ms.
2019-02-21 16:40:52,189 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7921ms.
2019-02-21 16:41:00,112 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11120ms.
2019-02-21 16:41:11,235 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13699ms.
2019-02-21 16:41:24,937 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20425ms.
2019-02-21 16:41:45,364 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11030ms.
2019-02-21 16:41:56,397 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21606ms.
2019-02-21 16:42:18,005 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18112ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:42:48,444 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1372ms.
2019-02-21 16:42:49,819 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2842ms.
2019-02-21 16:42:52,663 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4517ms.
2019-02-21 16:42:57,183 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10716ms.
2019-02-21 16:43:07,904 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8295ms.
2019-02-21 16:43:16,202 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17401ms.
2019-02-21 16:43:33,605 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8638ms.
2019-02-21 16:43:42,246 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15878ms.
2019-02-21 16:43:58,126 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17245ms.
2019-02-21 16:44:15,374 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19416ms.
2019-02-21 16:44:34,793 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 7717ms.
2019-02-21 16:44:42,512 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21963ms.
2019-02-21 16:45:04,478 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14979ms.
2019-02-21 16:45:19,460 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9998ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:45:41,704 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1348ms.
2019-02-21 16:45:43,055 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2078ms.
2019-02-21 16:45:45,135 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5132ms.
2019-02-21 16:45:50,272 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9727ms.
2019-02-21 16:46:00,002 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13156ms.
2019-02-21 16:46:13,160 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17717ms.
2019-02-21 16:46:30,880 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12944ms.
2019-02-21 16:46:43,827 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7531ms.
2019-02-21 16:46:51,360 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12758ms.
2019-02-21 16:47:04,121 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16081ms.
2019-02-21 16:47:20,204 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12339ms.
2019-02-21 16:47:32,546 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19797ms.
2019-02-21 16:47:52,345 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10180ms.
2019-02-21 16:48:02,528 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 10130ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:48:24,877 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 761ms.
2019-02-21 16:48:25,640 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1448ms.
2019-02-21 16:48:27,090 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5176ms.
2019-02-21 16:48:32,271 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5059ms.
2019-02-21 16:48:37,333 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12967ms.
2019-02-21 16:48:50,303 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19122ms.
2019-02-21 16:49:09,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22072ms.
2019-02-21 16:49:31,502 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8984ms.
2019-02-21 16:49:40,488 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9453ms.
2019-02-21 16:49:49,944 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20536ms.
2019-02-21 16:50:10,483 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14193ms.
2019-02-21 16:50:24,678 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18615ms.
2019-02-21 16:50:43,296 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18084ms.
2019-02-21 16:51:01,383 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15839ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:51:29,461 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1123ms.
2019-02-21 16:51:30,586 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2361ms.
2019-02-21 16:51:32,949 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2977ms.
2019-02-21 16:51:35,932 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5105ms.
2019-02-21 16:51:41,040 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17047ms.
2019-02-21 16:51:58,089 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16883ms.
2019-02-21 16:52:14,975 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18388ms.
2019-02-21 16:52:33,366 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21547ms.
2019-02-21 16:52:54,915 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 13643ms.
2019-02-21 16:53:08,561 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7975ms.
2019-02-21 16:53:16,539 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21622ms.
2019-02-21 16:53:38,163 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21869ms.
2019-02-21 16:54:00,035 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16419ms.
2019-02-21 16:54:16,457 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14633ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:54:43,313 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 938ms.
2019-02-21 16:54:44,254 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2917ms.
2019-02-21 16:54:47,173 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4877ms.
2019-02-21 16:54:52,055 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6973ms.
2019-02-21 16:54:59,031 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21180ms.
2019-02-21 16:55:20,214 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15367ms.
2019-02-21 16:55:35,583 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10378ms.
2019-02-21 16:55:45,964 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8226ms.
2019-02-21 16:55:54,192 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14183ms.
2019-02-21 16:56:08,378 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14683ms.
2019-02-21 16:56:23,064 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22419ms.
2019-02-21 16:56:45,486 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18251ms.
2019-02-21 16:57:03,739 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18403ms.
2019-02-21 16:57:22,145 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9275ms.
get: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 6 signal TERM catched and let quit gracefully
file 2 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile2: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile2': No such file or directory
2019-02-21 16:57:43,650 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1062ms.
2019-02-21 16:57:44,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1580ms.
2019-02-21 16:57:46,298 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5735ms.
2019-02-21 16:57:52,038 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10967ms.
2019-02-21 16:58:03,007 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12052ms.
2019-02-21 16:58:15,062 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19658ms.
2019-02-21 16:58:34,723 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22115ms.
2019-02-21 16:58:56,841 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17320ms.
2019-02-21 16:59:14,163 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 15442ms.
2019-02-21 16:59:29,608 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 18116ms.
2019-02-21 16:59:47,727 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9720ms.
2019-02-21 16:59:57,449 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 20385ms.
2019-02-21 17:00:17,837 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11426ms.
2019-02-21 17:00:29,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12446ms.
rm: Call From clnode076.clemson.cloudlab.us/130.127.133.85 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 2 has been removed from HDFS
