Found 20 items
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile1._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile10
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile11._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile12
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile13
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile14
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile15
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile16
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile17
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile18._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile19
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile20
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile4
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile5._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile6._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-27 00:20 /myfile7._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile8
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 00:21 /myfile9
file 9 has been put into HDFS
file 9 has been read from HDFS for 1 time
diff succeed!
file 9 has been read from HDFS for 2 time
diff succeed!
2019-02-27 00:22:10,128 INFO retry.RetryInvocationHandler: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.StandbyException): Operation category READ is not supported in state standby. Visit https://s.apache.org/sbnn-error
	at org.apache.hadoop.hdfs.server.namenode.ha.StandbyState.checkOperation(StandbyState.java:88)
	at org.apache.hadoop.hdfs.server.namenode.NameNode$NameNodeHAContext.checkOperation(NameNode.java:1952)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkOperation(FSNamesystem.java:1423)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getFileInfo(FSNamesystem.java:3085)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getFileInfo(NameNodeRpcServer.java:1154)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getFileInfo(ClientNamenodeProtocolServerSideTranslatorPB.java:966)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:872)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:818)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1729)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1160ms.
2019-02-27 00:22:11,291 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2084ms.
2019-02-27 00:22:13,378 INFO retry.RetryInvocationHandler: java.io.EOFException: End of File Exception between local host is: "clnode059.clemson.cloudlab.us/130.127.133.68"; destination host is: "node-1-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5458ms.
2019-02-27 00:22:18,838 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10657ms.
2019-02-27 00:22:29,500 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17529ms.
2019-02-27 00:22:47,031 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10005ms.
2019-02-27 00:22:57,039 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22284ms.
2019-02-27 00:23:19,325 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20129ms.
2019-02-27 00:23:39,457 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21481ms.
2019-02-27 00:24:00,940 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11889ms.
2019-02-27 00:24:12,832 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14936ms.
2019-02-27 00:24:27,770 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22263ms.
2019-02-27 00:24:50,036 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18147ms.
2019-02-27 00:25:08,186 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13062ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:25:33,477 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1478ms.
2019-02-27 00:25:34,958 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2775ms.
2019-02-27 00:25:37,734 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3736ms.
2019-02-27 00:25:41,476 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10305ms.
2019-02-27 00:25:51,784 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14572ms.
2019-02-27 00:26:06,358 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9581ms.
2019-02-27 00:26:15,942 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21361ms.
2019-02-27 00:26:37,305 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 15821ms.
2019-02-27 00:26:53,129 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10166ms.
2019-02-27 00:27:03,297 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13204ms.
2019-02-27 00:27:16,503 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22338ms.
2019-02-27 00:27:38,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10602ms.
2019-02-27 00:27:49,449 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15752ms.
2019-02-27 00:28:05,204 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11334ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:28:28,792 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 744ms.
2019-02-27 00:28:29,539 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2446ms.
2019-02-27 00:28:31,987 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3227ms.
2019-02-27 00:28:35,219 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8512ms.
2019-02-27 00:28:43,734 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21805ms.
2019-02-27 00:29:05,542 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20158ms.
2019-02-27 00:29:25,702 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10578ms.
2019-02-27 00:29:36,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 8433ms.
2019-02-27 00:29:44,718 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17051ms.
2019-02-27 00:30:01,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13652ms.
2019-02-27 00:30:15,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8883ms.
2019-02-27 00:30:24,313 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17601ms.
2019-02-27 00:30:41,916 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15483ms.
2019-02-27 00:30:57,403 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11295ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:31:20,963 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1273ms.
2019-02-27 00:31:22,239 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1114ms.
2019-02-27 00:31:23,354 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3526ms.
2019-02-27 00:31:26,885 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6266ms.
2019-02-27 00:31:33,154 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 11920ms.
2019-02-27 00:31:45,077 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12108ms.
2019-02-27 00:31:57,188 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 14454ms.
2019-02-27 00:32:11,644 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13852ms.
2019-02-27 00:32:25,499 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20019ms.
2019-02-27 00:32:45,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21295ms.
2019-02-27 00:33:06,818 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11554ms.
2019-02-27 00:33:18,375 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 9107ms.
2019-02-27 00:33:27,485 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 13617ms.
2019-02-27 00:33:41,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17368ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:34:10,714 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1075ms.
2019-02-27 00:34:11,792 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2849ms.
2019-02-27 00:34:14,643 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5111ms.
2019-02-27 00:34:19,760 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4092ms.
2019-02-27 00:34:23,854 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17173ms.
2019-02-27 00:34:41,030 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16003ms.
2019-02-27 00:34:57,036 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 20369ms.
2019-02-27 00:35:17,407 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 7996ms.
2019-02-27 00:35:25,405 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12946ms.
2019-02-27 00:35:38,354 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20957ms.
2019-02-27 00:35:59,313 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11954ms.
2019-02-27 00:36:11,270 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 16845ms.
2019-02-27 00:36:28,118 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16113ms.
2019-02-27 00:36:44,234 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16496ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:37:12,985 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1003ms.
2019-02-27 00:37:13,991 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1586ms.
2019-02-27 00:37:15,579 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4911ms.
2019-02-27 00:37:20,492 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7345ms.
2019-02-27 00:37:27,843 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13026ms.
2019-02-27 00:37:40,871 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10024ms.
2019-02-27 00:37:50,898 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10850ms.
2019-02-27 00:38:01,751 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19733ms.
2019-02-27 00:38:21,486 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18404ms.
2019-02-27 00:38:39,893 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 9536ms.
2019-02-27 00:38:49,431 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10182ms.
2019-02-27 00:38:59,616 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10703ms.
2019-02-27 00:39:10,321 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16248ms.
2019-02-27 00:39:26,572 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11357ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:39:50,151 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1468ms.
2019-02-27 00:39:51,622 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2918ms.
2019-02-27 00:39:54,543 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2300ms.
2019-02-27 00:39:56,848 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7211ms.
2019-02-27 00:40:04,061 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9740ms.
2019-02-27 00:40:13,804 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19613ms.
2019-02-27 00:40:33,420 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10672ms.
2019-02-27 00:40:44,095 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14840ms.
2019-02-27 00:40:58,938 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10129ms.
2019-02-27 00:41:09,069 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15066ms.
2019-02-27 00:41:24,137 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12766ms.
2019-02-27 00:41:36,906 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11211ms.
2019-02-27 00:41:48,120 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20676ms.
2019-02-27 00:42:08,799 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8237ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:42:29,304 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 880ms.
2019-02-27 00:42:30,187 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2720ms.
2019-02-27 00:42:32,909 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2763ms.
2019-02-27 00:42:35,678 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10336ms.
2019-02-27 00:42:46,017 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18669ms.
2019-02-27 00:43:04,689 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 12366ms.
2019-02-27 00:43:17,057 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11965ms.
2019-02-27 00:43:29,025 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9177ms.
2019-02-27 00:43:38,205 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16809ms.
2019-02-27 00:43:55,017 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17107ms.
2019-02-27 00:44:12,127 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8726ms.
2019-02-27 00:44:20,855 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18440ms.
2019-02-27 00:44:39,298 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20875ms.
2019-02-27 00:45:00,176 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17357ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:45:29,769 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 819ms.
2019-02-27 00:45:30,591 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2514ms.
2019-02-27 00:45:33,107 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5208ms.
2019-02-27 00:45:38,320 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4112ms.
2019-02-27 00:45:42,435 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14493ms.
2019-02-27 00:45:56,931 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17349ms.
2019-02-27 00:46:14,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16309ms.
2019-02-27 00:46:30,594 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11882ms.
2019-02-27 00:46:42,479 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10338ms.
2019-02-27 00:46:52,820 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 9661ms.
2019-02-27 00:47:02,483 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 13651ms.
2019-02-27 00:47:16,137 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15047ms.
2019-02-27 00:47:31,187 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9815ms.
2019-02-27 00:47:41,004 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19706ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been removed from HDFS
2019-02-27 00:48:12,913 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 617ms.
2019-02-27 00:48:13,533 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1240ms.
2019-02-27 00:48:14,774 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2593ms.
2019-02-27 00:48:17,369 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8257ms.
2019-02-27 00:48:25,631 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19020ms.
2019-02-27 00:48:44,654 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15994ms.
2019-02-27 00:49:00,650 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19084ms.
2019-02-27 00:49:19,737 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 14261ms.
2019-02-27 00:49:34,001 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21660ms.
2019-02-27 00:49:55,664 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17883ms.
2019-02-27 00:50:13,550 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14947ms.
2019-02-27 00:50:28,499 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17644ms.
2019-02-27 00:50:46,146 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20178ms.
2019-02-27 00:51:06,327 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12837ms.
put: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-27 00:51:21,279 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1007ms.
2019-02-27 00:51:22,289 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1435ms.
2019-02-27 00:51:23,726 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2987ms.
2019-02-27 00:51:26,719 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11443ms.
2019-02-27 00:51:38,164 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10940ms.
2019-02-27 00:51:49,107 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 7834ms.
2019-02-27 00:51:56,943 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16473ms.
2019-02-27 00:52:13,419 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17760ms.
2019-02-27 00:52:31,182 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9239ms.
2019-02-27 00:52:40,423 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17921ms.
2019-02-27 00:52:58,347 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20117ms.
2019-02-27 00:53:18,467 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18732ms.
2019-02-27 00:53:37,202 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21103ms.
2019-02-27 00:53:58,308 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13878ms.
ls: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been put into HDFS
2019-02-27 00:54:14,542 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 534ms.
2019-02-27 00:54:15,078 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1522ms.
2019-02-27 00:54:16,603 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5244ms.
2019-02-27 00:54:21,852 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9240ms.
2019-02-27 00:54:31,094 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10277ms.
2019-02-27 00:54:41,374 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17039ms.
2019-02-27 00:54:58,415 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13914ms.
2019-02-27 00:55:12,332 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13734ms.
2019-02-27 00:55:26,069 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 15576ms.
2019-02-27 00:55:41,647 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20192ms.
2019-02-27 00:56:01,842 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9528ms.
2019-02-27 00:56:11,373 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19009ms.
2019-02-27 00:56:30,385 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8641ms.
2019-02-27 00:56:39,028 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12671ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 00:57:03,936 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1338ms.
2019-02-27 00:57:05,277 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2679ms.
2019-02-27 00:57:07,959 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4524ms.
2019-02-27 00:57:12,486 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8325ms.
2019-02-27 00:57:20,815 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17911ms.
2019-02-27 00:57:38,730 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18526ms.
2019-02-27 00:57:57,259 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 17425ms.
2019-02-27 00:58:14,686 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17655ms.
2019-02-27 00:58:32,344 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 7886ms.
2019-02-27 00:58:40,233 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21317ms.
2019-02-27 00:59:01,552 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 18331ms.
2019-02-27 00:59:19,886 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18590ms.
2019-02-27 00:59:38,479 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10635ms.
2019-02-27 00:59:49,117 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16596ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 01:00:17,937 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1114ms.
2019-02-27 01:00:19,053 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2119ms.
2019-02-27 01:00:21,175 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4734ms.
2019-02-27 01:00:25,913 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7470ms.
2019-02-27 01:00:33,386 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10627ms.
2019-02-27 01:00:44,016 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14234ms.
2019-02-27 01:00:58,253 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19052ms.
2019-02-27 01:01:17,307 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17202ms.
2019-02-27 01:01:34,512 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9612ms.
2019-02-27 01:01:44,127 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14023ms.
2019-02-27 01:01:58,152 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 11288ms.
2019-02-27 01:02:09,443 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19647ms.
2019-02-27 01:02:29,092 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11909ms.
2019-02-27 01:02:41,004 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 20664ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 01:03:13,896 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 509ms.
2019-02-27 01:03:14,408 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2611ms.
2019-02-27 01:03:17,021 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2868ms.
2019-02-27 01:03:19,895 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5041ms.
2019-02-27 01:03:24,938 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 16228ms.
2019-02-27 01:03:41,169 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20660ms.
2019-02-27 01:04:01,832 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 20997ms.
2019-02-27 01:04:22,832 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 16412ms.
2019-02-27 01:04:39,247 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17323ms.
2019-02-27 01:04:56,572 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 12129ms.
2019-02-27 01:05:08,704 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15002ms.
2019-02-27 01:05:23,709 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8950ms.
2019-02-27 01:05:32,662 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15898ms.
2019-02-27 01:05:48,563 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18898ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 4 signal TERM catched and let quit gracefully
file 9 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile9: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile9': No such file or directory
2019-02-27 01:06:19,691 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1186ms.
2019-02-27 01:06:20,880 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1239ms.
2019-02-27 01:06:22,121 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3532ms.
2019-02-27 01:06:25,656 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11270ms.
2019-02-27 01:06:36,931 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21619ms.
2019-02-27 01:06:58,552 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17036ms.
2019-02-27 01:07:15,591 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11252ms.
2019-02-27 01:07:26,846 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20301ms.
2019-02-27 01:07:47,149 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16235ms.
2019-02-27 01:08:03,387 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10194ms.
2019-02-27 01:08:13,584 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12417ms.
2019-02-27 01:08:26,003 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 16057ms.
2019-02-27 01:08:42,063 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8535ms.
2019-02-27 01:08:50,600 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16208ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 9 has been removed from HDFS
