Found 20 items
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile10
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile11._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile12._COPYING_
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile13._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile14
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile15
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile16
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile17
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile18
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile19._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile20
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile4
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile5._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile6
-rw-r--r--   3 root supergroup  939524096 2019-02-20 03:09 /myfile7._COPYING_
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile8
-rw-r--r--   3 root supergroup 1073741824 2019-02-20 03:09 /myfile9
file 1 has been put into HDFS
file 1 has been read from HDFS for 1 time
diff succeed!
file 1 has been read from HDFS for 2 time
diff succeed!
file 1 has been read from HDFS for 3 time
diff succeed!
file 1 has been read from HDFS for 4 time
diff succeed!
2019-02-20 03:10:57,830 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 849ms.
2019-02-20 03:10:58,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1311ms.
2019-02-20 03:10:59,995 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3982ms.
2019-02-20 03:11:03,982 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5228ms.
2019-02-20 03:11:09,212 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19998ms.
2019-02-20 03:11:29,213 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19020ms.
2019-02-20 03:11:48,235 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10994ms.
2019-02-20 03:11:59,231 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 10666ms.
2019-02-20 03:12:09,900 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16877ms.
2019-02-20 03:12:26,779 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21620ms.
2019-02-20 03:12:48,401 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14732ms.
2019-02-20 03:13:03,136 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10382ms.
2019-02-20 03:13:13,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15501ms.
2019-02-20 03:13:29,024 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17697ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:13:58,951 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 765ms.
2019-02-20 03:13:59,719 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2799ms.
2019-02-20 03:14:02,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2479ms.
2019-02-20 03:14:05,002 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4096ms.
2019-02-20 03:14:09,103 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 7826ms.
2019-02-20 03:14:16,932 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18181ms.
2019-02-20 03:14:35,116 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19731ms.
2019-02-20 03:14:54,850 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19339ms.
2019-02-20 03:15:14,191 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 15724ms.
2019-02-20 03:15:29,918 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10085ms.
2019-02-20 03:15:40,005 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20521ms.
2019-02-20 03:16:00,529 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13322ms.
2019-02-20 03:16:13,854 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9160ms.
2019-02-20 03:16:23,016 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11199ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:16:46,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 588ms.
2019-02-20 03:16:47,017 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1990ms.
2019-02-20 03:16:49,009 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4524ms.
2019-02-20 03:16:53,538 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7408ms.
2019-02-20 03:17:00,949 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14927ms.
2019-02-20 03:17:15,879 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22493ms.
2019-02-20 03:17:38,375 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21033ms.
2019-02-20 03:17:59,410 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19443ms.
2019-02-20 03:18:18,856 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10911ms.
2019-02-20 03:18:29,769 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 19494ms.
2019-02-20 03:18:49,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9166ms.
2019-02-20 03:18:58,435 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8667ms.
2019-02-20 03:19:07,104 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9874ms.
2019-02-20 03:19:16,981 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 14029ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:19:43,265 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1273ms.
2019-02-20 03:19:44,541 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1993ms.
2019-02-20 03:19:46,536 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4565ms.
2019-02-20 03:19:51,106 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4559ms.
2019-02-20 03:19:55,667 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15825ms.
2019-02-20 03:20:11,495 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14897ms.
2019-02-20 03:20:26,394 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 7859ms.
2019-02-20 03:20:34,256 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17383ms.
2019-02-20 03:20:51,641 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 15866ms.
2019-02-20 03:21:07,510 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22062ms.
2019-02-20 03:21:29,574 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 19494ms.
2019-02-20 03:21:49,071 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13023ms.
2019-02-20 03:22:02,097 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14028ms.
2019-02-20 03:22:16,127 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11818ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:22:40,164 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1189ms.
2019-02-20 03:22:41,356 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2283ms.
2019-02-20 03:22:43,641 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2610ms.
2019-02-20 03:22:46,257 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9779ms.
2019-02-20 03:22:56,038 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8999ms.
2019-02-20 03:23:05,040 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10480ms.
2019-02-20 03:23:15,523 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 17386ms.
2019-02-20 03:23:32,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 20650ms.
2019-02-20 03:23:53,565 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11485ms.
2019-02-20 03:24:05,053 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7817ms.
2019-02-20 03:24:12,872 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12035ms.
2019-02-20 03:24:24,909 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21385ms.
2019-02-20 03:24:46,297 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16892ms.
2019-02-20 03:25:03,191 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 16039ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:25:31,485 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 998ms.
2019-02-20 03:25:32,486 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1370ms.
2019-02-20 03:25:33,859 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3580ms.
2019-02-20 03:25:37,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10523ms.
2019-02-20 03:25:47,970 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15605ms.
2019-02-20 03:26:03,578 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 19801ms.
2019-02-20 03:26:23,381 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10388ms.
2019-02-20 03:26:33,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19237ms.
2019-02-20 03:26:53,012 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20903ms.
2019-02-20 03:27:13,917 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17599ms.
2019-02-20 03:27:31,519 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 7555ms.
2019-02-20 03:27:39,077 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19130ms.
2019-02-20 03:27:58,210 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15922ms.
2019-02-20 03:28:14,134 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 20892ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:28:47,268 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1345ms.
2019-02-20 03:28:48,616 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2320ms.
2019-02-20 03:28:50,938 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3072ms.
2019-02-20 03:28:54,013 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4261ms.
2019-02-20 03:28:58,278 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9848ms.
2019-02-20 03:29:08,128 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20903ms.
2019-02-20 03:29:29,034 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 16231ms.
2019-02-20 03:29:45,268 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12676ms.
2019-02-20 03:29:57,946 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20878ms.
2019-02-20 03:30:18,827 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 11244ms.
2019-02-20 03:30:30,074 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21485ms.
2019-02-20 03:30:51,561 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18213ms.
2019-02-20 03:31:09,777 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14166ms.
2019-02-20 03:31:23,946 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13274ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been removed from HDFS
2019-02-20 03:31:49,445 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 526ms.
2019-02-20 03:31:49,974 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2589ms.
2019-02-20 03:31:52,565 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4501ms.
2019-02-20 03:31:57,072 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6808ms.
2019-02-20 03:32:03,883 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 13968ms.
2019-02-20 03:32:17,853 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17899ms.
2019-02-20 03:32:35,755 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 13721ms.
2019-02-20 03:32:49,479 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12268ms.
2019-02-20 03:33:01,749 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12047ms.
2019-02-20 03:33:13,799 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21269ms.
2019-02-20 03:33:35,071 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12485ms.
2019-02-20 03:33:47,559 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22082ms.
2019-02-20 03:34:09,643 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 9723ms.
2019-02-20 03:34:19,369 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 9816ms.
put: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-20 03:34:31,298 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 820ms.
2019-02-20 03:34:32,121 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1927ms.
2019-02-20 03:34:34,049 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5657ms.
2019-02-20 03:34:39,712 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5270ms.
2019-02-20 03:34:44,984 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20567ms.
2019-02-20 03:35:05,554 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 8882ms.
2019-02-20 03:35:14,438 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 14895ms.
2019-02-20 03:35:29,336 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13103ms.
2019-02-20 03:35:42,441 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12348ms.
2019-02-20 03:35:54,792 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7655ms.
2019-02-20 03:36:02,450 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15247ms.
2019-02-20 03:36:17,699 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17210ms.
2019-02-20 03:36:34,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8287ms.
2019-02-20 03:36:43,202 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13560ms.
ls: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been put into HDFS
2019-02-20 03:36:59,050 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1489ms.
2019-02-20 03:37:00,541 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2989ms.
2019-02-20 03:37:03,532 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4731ms.
2019-02-20 03:37:08,266 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 7767ms.
2019-02-20 03:37:16,038 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14962ms.
2019-02-20 03:37:31,003 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17766ms.
2019-02-20 03:37:48,771 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9405ms.
2019-02-20 03:37:58,179 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17250ms.
2019-02-20 03:38:15,432 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 17946ms.
2019-02-20 03:38:33,381 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8408ms.
2019-02-20 03:38:41,791 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 17824ms.
2019-02-20 03:38:59,618 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10598ms.
2019-02-20 03:39:10,218 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21316ms.
2019-02-20 03:39:31,537 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19845ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:40:03,643 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1122ms.
2019-02-20 03:40:04,768 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1463ms.
2019-02-20 03:40:06,233 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5630ms.
2019-02-20 03:40:11,868 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 5424ms.
2019-02-20 03:40:17,295 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12496ms.
2019-02-20 03:40:29,794 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22163ms.
2019-02-20 03:40:51,960 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18924ms.
2019-02-20 03:41:10,887 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 18677ms.
2019-02-20 03:41:29,566 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 10295ms.
2019-02-20 03:41:39,863 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 13163ms.
2019-02-20 03:41:53,029 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10262ms.
2019-02-20 03:42:03,294 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 7781ms.
2019-02-20 03:42:11,078 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18071ms.
2019-02-20 03:42:29,152 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 22401ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:43:03,811 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1148ms.
2019-02-20 03:43:04,962 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2360ms.
2019-02-20 03:43:07,323 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3546ms.
2019-02-20 03:43:10,874 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4422ms.
2019-02-20 03:43:15,299 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 21461ms.
2019-02-20 03:43:36,762 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20813ms.
2019-02-20 03:43:57,578 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 7686ms.
2019-02-20 03:44:05,267 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 22110ms.
2019-02-20 03:44:27,379 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18650ms.
2019-02-20 03:44:46,032 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16690ms.
2019-02-20 03:45:02,724 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22155ms.
2019-02-20 03:45:24,882 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21311ms.
2019-02-20 03:45:46,196 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 18228ms.
2019-02-20 03:46:04,427 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13937ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:46:30,586 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1165ms.
2019-02-20 03:46:31,754 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2710ms.
2019-02-20 03:46:34,466 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5922ms.
2019-02-20 03:46:40,390 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4505ms.
2019-02-20 03:46:44,900 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18458ms.
2019-02-20 03:47:03,361 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11351ms.
2019-02-20 03:47:14,715 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8857ms.
2019-02-20 03:47:23,574 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19830ms.
2019-02-20 03:47:43,407 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 8140ms.
2019-02-20 03:47:51,550 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 20562ms.
2019-02-20 03:48:12,115 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16616ms.
2019-02-20 03:48:28,734 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 17431ms.
2019-02-20 03:48:46,168 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8493ms.
2019-02-20 03:48:54,663 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11625ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:49:18,530 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1151ms.
2019-02-20 03:49:19,684 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1049ms.
2019-02-20 03:49:20,736 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3071ms.
2019-02-20 03:49:23,809 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11684ms.
2019-02-20 03:49:35,498 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17406ms.
2019-02-20 03:49:52,907 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 22245ms.
2019-02-20 03:50:15,155 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19176ms.
2019-02-20 03:50:34,334 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19942ms.
2019-02-20 03:50:54,278 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 13631ms.
2019-02-20 03:51:07,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16593ms.
2019-02-20 03:51:24,508 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 7864ms.
2019-02-20 03:51:32,375 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 18153ms.
2019-02-20 03:51:50,530 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 19840ms.
2019-02-20 03:52:10,373 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 17079ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:52:39,681 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 829ms.
2019-02-20 03:52:40,512 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2911ms.
2019-02-20 03:52:43,425 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 2063ms.
2019-02-20 03:52:45,494 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8459ms.
2019-02-20 03:52:53,955 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19516ms.
2019-02-20 03:53:13,474 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 14763ms.
2019-02-20 03:53:28,239 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 18318ms.
2019-02-20 03:53:46,560 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19614ms.
2019-02-20 03:54:06,177 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16405ms.
2019-02-20 03:54:22,585 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 9901ms.
2019-02-20 03:54:32,489 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 12462ms.
2019-02-20 03:54:44,954 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 19761ms.
2019-02-20 03:55:04,717 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14253ms.
2019-02-20 03:55:18,973 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19163ms.
get: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 6 signal TERM catched and let quit gracefully
file 1 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile1: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile1': No such file or directory
2019-02-20 03:55:50,358 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 651ms.
2019-02-20 03:55:51,011 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2204ms.
2019-02-20 03:55:53,217 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4149ms.
2019-02-20 03:55:57,369 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6593ms.
2019-02-20 03:56:03,966 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14708ms.
2019-02-20 03:56:18,677 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 16059ms.
2019-02-20 03:56:34,739 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9282ms.
2019-02-20 03:56:44,023 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11657ms.
2019-02-20 03:56:55,683 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20125ms.
2019-02-20 03:57:15,811 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 17289ms.
2019-02-20 03:57:33,103 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 22255ms.
2019-02-20 03:57:55,361 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 16265ms.
2019-02-20 03:58:11,629 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 10912ms.
2019-02-20 03:58:22,543 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19226ms.
rm: Call From clnode090.clemson.cloudlab.us/130.127.133.99 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 1 has been removed from HDFS
