Found 20 items
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile1
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile10
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile11
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile12
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile13
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile14
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile15
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile16
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile17
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile18
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile19
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile2
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile20
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile3
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile4
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile5
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile6
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile7
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile8
-rw-r--r--   3 root supergroup 1073741824 2019-02-27 03:47 /myfile9
file 17 has been put into HDFS
file 17 has been read from HDFS for 1 time
diff succeed!
file 17 has been read from HDFS for 2 time
diff succeed!
file 17 has been read from HDFS for 3 time
diff succeed!
2019-02-27 03:48:39,923 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1364ms.
2019-02-27 03:48:41,290 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2030ms.
2019-02-27 03:48:43,322 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5342ms.
2019-02-27 03:48:48,670 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 10930ms.
2019-02-27 03:49:00,349 INFO retry.RetryInvocationHandler: java.io.EOFException: End of File Exception between local host is: "clnode059.clemson.cloudlab.us/130.127.133.68"; destination host is: "node-1-link-0":8020; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 18024ms.
2019-02-27 03:49:18,376 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 9724ms.
2019-02-27 03:49:28,102 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11379ms.
2019-02-27 03:49:39,483 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11277ms.
2019-02-27 03:49:50,763 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11650ms.
2019-02-27 03:50:02,415 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10771ms.
2019-02-27 03:50:13,188 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20892ms.
2019-02-27 03:50:34,083 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 15527ms.
2019-02-27 03:50:49,612 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 17701ms.
2019-02-27 03:51:07,316 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 21704ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 03:51:41,246 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1266ms.
2019-02-27 03:51:42,515 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2235ms.
2019-02-27 03:51:44,752 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4843ms.
2019-02-27 03:51:49,600 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11608ms.
2019-02-27 03:52:01,211 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15662ms.
2019-02-27 03:52:16,875 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13294ms.
2019-02-27 03:52:30,172 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19296ms.
2019-02-27 03:52:49,470 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 17592ms.
2019-02-27 03:53:07,065 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 8457ms.
2019-02-27 03:53:15,524 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10156ms.
2019-02-27 03:53:25,682 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 10506ms.
2019-02-27 03:53:36,190 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14421ms.
2019-02-27 03:53:50,614 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12684ms.
2019-02-27 03:54:03,300 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13581ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 03:54:29,134 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1200ms.
2019-02-27 03:54:30,337 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2463ms.
2019-02-27 03:54:32,802 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3310ms.
2019-02-27 03:54:36,117 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9669ms.
2019-02-27 03:54:45,789 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10748ms.
2019-02-27 03:54:56,540 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 11555ms.
2019-02-27 03:55:08,097 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19226ms.
2019-02-27 03:55:27,326 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21453ms.
2019-02-27 03:55:48,781 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 20721ms.
2019-02-27 03:56:09,505 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14653ms.
2019-02-27 03:56:24,160 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 20681ms.
2019-02-27 03:56:44,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 13628ms.
2019-02-27 03:56:58,474 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 20874ms.
2019-02-27 03:57:19,351 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19963ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 6 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 03:57:51,581 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 722ms.
2019-02-27 03:57:52,306 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2398ms.
2019-02-27 03:57:54,706 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5694ms.
2019-02-27 03:58:00,403 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4815ms.
2019-02-27 03:58:05,223 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 17166ms.
2019-02-27 03:58:22,392 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 7620ms.
2019-02-27 03:58:30,015 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 12010ms.
2019-02-27 03:58:42,028 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13484ms.
2019-02-27 03:58:55,514 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 11550ms.
2019-02-27 03:59:07,066 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 10691ms.
2019-02-27 03:59:17,760 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15208ms.
2019-02-27 03:59:32,970 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 8585ms.
2019-02-27 03:59:41,557 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12658ms.
2019-02-27 03:59:54,218 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 12338ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 7 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:00:18,790 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1288ms.
2019-02-27 04:00:20,081 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1605ms.
2019-02-27 04:00:21,689 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5603ms.
2019-02-27 04:00:27,295 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9531ms.
2019-02-27 04:00:36,831 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20297ms.
2019-02-27 04:00:57,131 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10024ms.
2019-02-27 04:01:07,157 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 11153ms.
2019-02-27 04:01:18,313 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9192ms.
2019-02-27 04:01:27,508 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 19840ms.
2019-02-27 04:01:47,351 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 15406ms.
2019-02-27 04:02:02,759 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 7865ms.
2019-02-27 04:02:10,627 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11956ms.
2019-02-27 04:02:22,585 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8858ms.
2019-02-27 04:02:31,446 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8558ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 8 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:02:52,250 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1005ms.
2019-02-27 04:02:53,258 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1038ms.
2019-02-27 04:02:54,298 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4012ms.
2019-02-27 04:02:58,312 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4371ms.
2019-02-27 04:03:02,687 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 8513ms.
2019-02-27 04:03:11,203 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13076ms.
2019-02-27 04:03:24,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19628ms.
2019-02-27 04:03:43,914 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 16195ms.
2019-02-27 04:04:00,111 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9797ms.
2019-02-27 04:04:09,911 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7714ms.
2019-02-27 04:04:17,628 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21080ms.
2019-02-27 04:04:38,711 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12058ms.
2019-02-27 04:04:50,772 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15196ms.
2019-02-27 04:05:05,970 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 20096ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 9 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:05:38,338 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 531ms.
2019-02-27 04:05:38,871 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1216ms.
2019-02-27 04:05:40,089 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3753ms.
2019-02-27 04:05:43,844 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9800ms.
2019-02-27 04:05:53,649 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 22494ms.
2019-02-27 04:06:16,147 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18174ms.
2019-02-27 04:06:34,323 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 19490ms.
2019-02-27 04:06:53,816 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9376ms.
2019-02-27 04:07:03,195 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 22344ms.
2019-02-27 04:07:25,542 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22239ms.
2019-02-27 04:07:47,784 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21217ms.
2019-02-27 04:08:09,003 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22215ms.
2019-02-27 04:08:31,221 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12019ms.
2019-02-27 04:08:43,243 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 22116ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 10 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:09:17,604 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1411ms.
2019-02-27 04:09:19,018 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2172ms.
2019-02-27 04:09:21,193 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3122ms.
2019-02-27 04:09:24,317 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9265ms.
2019-02-27 04:09:33,587 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 15504ms.
2019-02-27 04:09:49,094 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20299ms.
2019-02-27 04:10:09,396 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 15166ms.
2019-02-27 04:10:24,565 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19690ms.
2019-02-27 04:10:44,258 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16490ms.
2019-02-27 04:11:00,751 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 21994ms.
2019-02-27 04:11:22,747 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 15564ms.
2019-02-27 04:11:38,314 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 14129ms.
2019-02-27 04:11:52,445 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21448ms.
2019-02-27 04:12:13,896 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 19648ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been removed from HDFS
2019-02-27 04:12:45,783 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1126ms.
2019-02-27 04:12:46,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1765ms.
2019-02-27 04:12:48,679 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5744ms.
2019-02-27 04:12:54,425 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6493ms.
2019-02-27 04:13:00,924 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 10894ms.
2019-02-27 04:13:11,820 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 20960ms.
2019-02-27 04:13:32,783 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 9462ms.
2019-02-27 04:13:42,247 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 21025ms.
2019-02-27 04:14:03,275 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 13980ms.
2019-02-27 04:14:17,257 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8988ms.
2019-02-27 04:14:26,248 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9769ms.
2019-02-27 04:14:36,019 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 11469ms.
2019-02-27 04:14:47,491 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 14329ms.
2019-02-27 04:15:01,823 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11973ms.
put: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
2019-02-27 04:15:15,936 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1191ms.
2019-02-27 04:15:17,130 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2699ms.
2019-02-27 04:15:19,831 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5688ms.
2019-02-27 04:15:25,525 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9923ms.
2019-02-27 04:15:35,451 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 20894ms.
2019-02-27 04:15:56,348 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13046ms.
2019-02-27 04:16:09,397 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 10488ms.
2019-02-27 04:16:19,888 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 19761ms.
2019-02-27 04:16:39,651 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9723ms.
2019-02-27 04:16:49,377 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 14216ms.
2019-02-27 04:17:03,595 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 14240ms.
2019-02-27 04:17:17,838 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22383ms.
2019-02-27 04:17:40,224 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12125ms.
2019-02-27 04:17:52,352 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 8674ms.
ls: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been put into HDFS
2019-02-27 04:18:03,371 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 604ms.
2019-02-27 04:18:03,979 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1716ms.
2019-02-27 04:18:05,697 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5874ms.
2019-02-27 04:18:11,577 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 4414ms.
2019-02-27 04:18:15,993 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 19398ms.
2019-02-27 04:18:35,395 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13811ms.
2019-02-27 04:18:49,209 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 22266ms.
2019-02-27 04:19:11,478 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13958ms.
2019-02-27 04:19:25,438 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 16417ms.
2019-02-27 04:19:41,858 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 8340ms.
2019-02-27 04:19:50,200 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21808ms.
2019-02-27 04:20:12,012 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 21424ms.
2019-02-27 04:20:33,439 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 16395ms.
2019-02-27 04:20:49,836 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 18609ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 1 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:21:20,706 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1337ms.
2019-02-27 04:21:22,047 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2268ms.
2019-02-27 04:21:24,317 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 5975ms.
2019-02-27 04:21:30,295 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 6466ms.
2019-02-27 04:21:36,766 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 11574ms.
2019-02-27 04:21:48,342 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 15432ms.
2019-02-27 04:22:03,777 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21516ms.
2019-02-27 04:22:25,296 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13229ms.
2019-02-27 04:22:38,527 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 14985ms.
2019-02-27 04:22:53,515 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7501ms.
2019-02-27 04:23:01,018 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 21052ms.
2019-02-27 04:23:22,073 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12153ms.
2019-02-27 04:23:34,229 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 21223ms.
2019-02-27 04:23:55,455 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 10636ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 2 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:24:18,378 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1139ms.
2019-02-27 04:24:19,520 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 2151ms.
2019-02-27 04:24:21,674 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 4367ms.
2019-02-27 04:24:26,046 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11230ms.
2019-02-27 04:24:37,279 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 14374ms.
2019-02-27 04:24:51,656 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 17808ms.
2019-02-27 04:25:09,466 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 17433ms.
2019-02-27 04:25:26,902 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 13017ms.
2019-02-27 04:25:39,922 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 21544ms.
2019-02-27 04:26:01,469 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16298ms.
2019-02-27 04:26:17,769 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 16972ms.
2019-02-27 04:26:34,745 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 10784ms.
2019-02-27 04:26:45,532 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 11093ms.
2019-02-27 04:26:56,627 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 10591ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 3 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:27:19,457 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 997ms.
2019-02-27 04:27:20,457 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1992ms.
2019-02-27 04:27:22,451 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3149ms.
2019-02-27 04:27:25,605 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 11675ms.
2019-02-27 04:27:37,283 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 12628ms.
2019-02-27 04:27:49,914 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 18995ms.
2019-02-27 04:28:08,912 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 21254ms.
2019-02-27 04:28:30,169 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 9149ms.
2019-02-27 04:28:39,320 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 18644ms.
2019-02-27 04:28:57,967 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 16690ms.
2019-02-27 04:29:14,660 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 9162ms.
2019-02-27 04:29:23,825 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12257ms.
2019-02-27 04:29:36,085 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 15356ms.
2019-02-27 04:29:51,443 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 15775ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been read from HDFS for 4 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:30:19,462 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1251ms.
2019-02-27 04:30:20,716 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1123ms.
2019-02-27 04:30:21,841 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3453ms.
2019-02-27 04:30:25,300 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 8064ms.
2019-02-27 04:30:33,367 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9949ms.
2019-02-27 04:30:43,319 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 13534ms.
2019-02-27 04:30:56,856 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 15256ms.
2019-02-27 04:31:12,115 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 11421ms.
2019-02-27 04:31:23,539 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 9733ms.
2019-02-27 04:31:33,274 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 22347ms.
2019-02-27 04:31:55,623 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 8362ms.
2019-02-27 04:32:03,988 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 22018ms.
2019-02-27 04:32:26,009 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 8361ms.
2019-02-27 04:32:34,373 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 13437ms.
get: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
sub_benchmark 5 signal TERM catched and let quit gracefully
file 17 has been read from HDFS for 5 time
diff: /root/my_large_file/tmp/myfile17: No such file or directory
diff succeed!
rm: cannot remove '/root/my_large_file/tmp/myfile17': No such file or directory
2019-02-27 04:33:00,066 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 1 failover attempts. Trying to failover after sleeping for 1464ms.
2019-02-27 04:33:01,533 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 2 failover attempts. Trying to failover after sleeping for 1135ms.
2019-02-27 04:33:02,670 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 3 failover attempts. Trying to failover after sleeping for 3918ms.
2019-02-27 04:33:06,594 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 4 failover attempts. Trying to failover after sleeping for 9812ms.
2019-02-27 04:33:16,409 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 5 failover attempts. Trying to failover after sleeping for 9895ms.
2019-02-27 04:33:26,306 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 6 failover attempts. Trying to failover after sleeping for 10481ms.
2019-02-27 04:33:36,790 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 7 failover attempts. Trying to failover after sleeping for 8419ms.
2019-02-27 04:33:45,212 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 8 failover attempts. Trying to failover after sleeping for 12191ms.
2019-02-27 04:33:57,406 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 9 failover attempts. Trying to failover after sleeping for 12039ms.
2019-02-27 04:34:09,448 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 10 failover attempts. Trying to failover after sleeping for 7663ms.
2019-02-27 04:34:17,113 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 11 failover attempts. Trying to failover after sleeping for 18661ms.
2019-02-27 04:34:35,777 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 12 failover attempts. Trying to failover after sleeping for 12223ms.
2019-02-27 04:34:48,003 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-1-link-0/10.10.1.4:8020 after 13 failover attempts. Trying to failover after sleeping for 12310ms.
2019-02-27 04:35:00,316 INFO retry.RetryInvocationHandler: java.net.ConnectException: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-0-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over node-0-link-0/10.10.1.1:8020 after 14 failover attempts. Trying to failover after sleeping for 11428ms.
rm: Call From clnode059.clemson.cloudlab.us/130.127.133.68 to node-1-link-0:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
file 17 has been removed from HDFS
